// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveReferences = `-- name: CountActiveReferences :one
SELECT count(*) FROM asset_references
WHERE asset_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountActiveReferences(ctx context.Context, assetID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveReferences, assetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (original_filename, name, mime_type, size_bytes, checksum_sha256, width, height, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, original_filename, name, mime_type, size_bytes, checksum_sha256, width, height, uploaded_by, created_at, updated_at
`

type CreateAssetParams struct {
	OriginalFilename string `json:"original_filename"`
	Name             string `json:"name"`
	MimeType         string `json:"mime_type"`
	SizeBytes        int64  `json:"size_bytes"`
	ChecksumSha256   string `json:"checksum_sha256"`
	Width            *int32 `json:"width"`
	Height           *int32 `json:"height"`
	UploadedBy       int64  `json:"uploaded_by"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.OriginalFilename,
		arg.Name,
		arg.MimeType,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.Width,
		arg.Height,
		arg.UploadedBy,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.Name,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Width,
		&i.Height,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssetReference = `-- name: CreateAssetReference :one
INSERT INTO asset_references (asset_id, space_id, folder_id)
VALUES ($1, $2, $3)
RETURNING id, asset_id, space_id, folder_id, created_at, deleted_at
`

type CreateAssetReferenceParams struct {
	AssetID  uuid.UUID   `json:"asset_id"`
	SpaceID  uuid.UUID   `json:"space_id"`
	FolderID pgtype.UUID `json:"folder_id"`
}

func (q *Queries) CreateAssetReference(ctx context.Context, arg CreateAssetReferenceParams) (AssetReference, error) {
	row := q.db.QueryRow(ctx, createAssetReference, arg.AssetID, arg.SpaceID, arg.FolderID)
	var i AssetReference
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.SpaceID,
		&i.FolderID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssetByChecksum = `-- name: GetAssetByChecksum :one
SELECT id, original_filename, name, mime_type, size_bytes, checksum_sha256, width, height, uploaded_by, created_at, updated_at FROM assets WHERE checksum_sha256 = $1
`

func (q *Queries) GetAssetByChecksum(ctx context.Context, checksumSha256 string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByChecksum, checksumSha256)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.Name,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Width,
		&i.Height,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, original_filename, name, mime_type, size_bytes, checksum_sha256, width, height, uploaded_by, created_at, updated_at FROM assets WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id uuid.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.Name,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Width,
		&i.Height,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssetsByFolder = `-- name: ListAssetsByFolder :many
SELECT a.id, a.original_filename, a.name, a.mime_type, a.size_bytes, a.checksum_sha256, a.width, a.height, a.uploaded_by, a.created_at, a.updated_at FROM assets a
JOIN asset_references ar ON ar.asset_id = a.id
WHERE ar.space_id = $1 AND ar.folder_id = $2 AND ar.deleted_at IS NULL
ORDER BY a.created_at DESC
LIMIT $3 OFFSET $4
`

type ListAssetsByFolderParams struct {
	SpaceID  uuid.UUID   `json:"space_id"`
	FolderID pgtype.UUID `json:"folder_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListAssetsByFolder(ctx context.Context, arg ListAssetsByFolderParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByFolder,
		arg.SpaceID,
		arg.FolderID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.Name,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.Width,
			&i.Height,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsBySpace = `-- name: ListAssetsBySpace :many
SELECT a.id, a.original_filename, a.name, a.mime_type, a.size_bytes, a.checksum_sha256, a.width, a.height, a.uploaded_by, a.created_at, a.updated_at FROM assets a
JOIN asset_references ar ON ar.asset_id = a.id
WHERE ar.space_id = $1 AND ar.deleted_at IS NULL
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAssetsBySpaceParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListAssetsBySpace(ctx context.Context, arg ListAssetsBySpaceParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsBySpace, arg.SpaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.Name,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.Width,
			&i.Height,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsBySpaceRoot = `-- name: ListAssetsBySpaceRoot :many
SELECT a.id, a.original_filename, a.name, a.mime_type, a.size_bytes, a.checksum_sha256, a.width, a.height, a.uploaded_by, a.created_at, a.updated_at FROM assets a
JOIN asset_references ar ON ar.asset_id = a.id
WHERE ar.space_id = $1 AND ar.folder_id IS NULL AND ar.deleted_at IS NULL
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAssetsBySpaceRootParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListAssetsBySpaceRoot(ctx context.Context, arg ListAssetsBySpaceRootParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsBySpaceRoot, arg.SpaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.Name,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.Width,
			&i.Height,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedAssets = `-- name: ListOrphanedAssets :many
SELECT a.id FROM assets a
WHERE NOT EXISTS (
    SELECT 1 FROM asset_references ar
    WHERE ar.asset_id = a.id AND ar.deleted_at IS NULL
)
AND a.created_at < $1
`

func (q *Queries) ListOrphanedAssets(ctx context.Context, createdAt time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOrphanedAssets, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedReferences = `-- name: ListTrashedReferences :many
SELECT ar.id, ar.asset_id, ar.space_id, ar.folder_id, ar.created_at, ar.deleted_at, a.name, a.mime_type, a.size_bytes
FROM asset_references ar
JOIN assets a ON a.id = ar.asset_id
WHERE ar.space_id = $1 AND ar.deleted_at IS NOT NULL
ORDER BY ar.deleted_at DESC
`

type ListTrashedReferencesRow struct {
	ID        int64              `json:"id"`
	AssetID   uuid.UUID          `json:"asset_id"`
	SpaceID   uuid.UUID          `json:"space_id"`
	FolderID  pgtype.UUID        `json:"folder_id"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Name      string             `json:"name"`
	MimeType  string             `json:"mime_type"`
	SizeBytes int64              `json:"size_bytes"`
}

func (q *Queries) ListTrashedReferences(ctx context.Context, spaceID uuid.UUID) ([]ListTrashedReferencesRow, error) {
	rows, err := q.db.Query(ctx, listTrashedReferences, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrashedReferencesRow{}
	for rows.Next() {
		var i ListTrashedReferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.SpaceID,
			&i.FolderID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.MimeType,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAssetReference = `-- name: RestoreAssetReference :exec
UPDATE asset_references
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreAssetReference(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreAssetReference, id)
	return err
}

const softDeleteAssetReference = `-- name: SoftDeleteAssetReference :exec
UPDATE asset_references
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteAssetReference(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteAssetReference, id)
	return err
}

const updateAssetName = `-- name: UpdateAssetName :exec
UPDATE assets SET name = $2, updated_at = now() WHERE id = $1
`

type UpdateAssetNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateAssetName(ctx context.Context, arg UpdateAssetNameParams) error {
	_, err := q.db.Exec(ctx, updateAssetName, arg.ID, arg.Name)
	return err
}
