// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clerk_webhook_events.sql

package db

import (
	"context"
)

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO clerk_webhook_events (event_id, event_type, payload)
VALUES ($1, $2, $3)
ON CONFLICT (event_id) DO NOTHING
RETURNING id
`

type InsertWebhookEventParams struct {
	EventID   string `json:"event_id"`
	EventType string `json:"event_type"`
	Payload   []byte `json:"payload"`
}

// Returns the new row id only when inserted; ON CONFLICT (duplicate delivery)
// returns no rows, which the caller treats as "already seen" (idempotent).
func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent, arg.EventID, arg.EventType, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markWebhookFailed = `-- name: MarkWebhookFailed :exec
UPDATE clerk_webhook_events
SET error = $2
WHERE id = $1
`

type MarkWebhookFailedParams struct {
	ID    int64   `json:"id"`
	Error *string `json:"error"`
}

func (q *Queries) MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookFailed, arg.ID, arg.Error)
	return err
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE clerk_webhook_events
SET processed_at = now(),
    error = NULL
WHERE id = $1
`

func (q *Queries) MarkWebhookProcessed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, id)
	return err
}
