// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveJobHealth = `-- name: ArchiveJobHealth :one
SELECT
    count(*) FILTER (WHERE status = 'pending')   AS pending,
    count(*) FILTER (WHERE status = 'running')   AS running,
    count(*) FILTER (WHERE status = 'completed') AS completed,
    count(*) FILTER (WHERE status = 'failed')    AS failed
FROM archive_sync_jobs
`

type ArchiveJobHealthRow struct {
	Pending   int64 `json:"pending"`
	Running   int64 `json:"running"`
	Completed int64 `json:"completed"`
	Failed    int64 `json:"failed"`
}

func (q *Queries) ArchiveJobHealth(ctx context.Context) (ArchiveJobHealthRow, error) {
	row := q.db.QueryRow(ctx, archiveJobHealth)
	var i ArchiveJobHealthRow
	err := row.Scan(
		&i.Pending,
		&i.Running,
		&i.Completed,
		&i.Failed,
	)
	return i, err
}

const spaceAssetCountsByType = `-- name: SpaceAssetCountsByType :many
SELECT type, count(*) AS count
FROM assets
WHERE space_id = $1 AND deleted_at IS NULL
GROUP BY type
ORDER BY count DESC
`

type SpaceAssetCountsByTypeRow struct {
	Type  string `json:"type"`
	Count int64  `json:"count"`
}

func (q *Queries) SpaceAssetCountsByType(ctx context.Context, spaceID int64) ([]SpaceAssetCountsByTypeRow, error) {
	rows, err := q.db.Query(ctx, spaceAssetCountsByType, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpaceAssetCountsByTypeRow{}
	for rows.Next() {
		var i SpaceAssetCountsByTypeRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spaceAssetStats = `-- name: SpaceAssetStats :one
SELECT
    count(*)                        AS total_assets,
    COALESCE(sum(size), 0)::bigint  AS total_size,
    count(DISTINCT type)            AS type_count
FROM assets
WHERE space_id = $1 AND deleted_at IS NULL
`

type SpaceAssetStatsRow struct {
	TotalAssets int64 `json:"total_assets"`
	TotalSize   int64 `json:"total_size"`
	TypeCount   int64 `json:"type_count"`
}

func (q *Queries) SpaceAssetStats(ctx context.Context, spaceID int64) (SpaceAssetStatsRow, error) {
	row := q.db.QueryRow(ctx, spaceAssetStats, spaceID)
	var i SpaceAssetStatsRow
	err := row.Scan(&i.TotalAssets, &i.TotalSize, &i.TypeCount)
	return i, err
}

const spaceRecentAssets = `-- name: SpaceRecentAssets :many
SELECT id, name, type, mime_type, size, created_at
FROM assets
WHERE space_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type SpaceRecentAssetsParams struct {
	SpaceID int64 `json:"space_id"`
	Limit   int32 `json:"limit"`
}

type SpaceRecentAssetsRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	MimeType  string    `json:"mime_type"`
	Size      int64     `json:"size"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) SpaceRecentAssets(ctx context.Context, arg SpaceRecentAssetsParams) ([]SpaceRecentAssetsRow, error) {
	rows, err := q.db.Query(ctx, spaceRecentAssets, arg.SpaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpaceRecentAssetsRow{}
	for rows.Next() {
		var i SpaceRecentAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
