// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (space_id, parent_id, name)
VALUES ($1, $2, $3)
RETURNING id, space_id, parent_id, name, created_at, updated_at, deleted_at
`

type CreateFolderParams struct {
	SpaceID  uuid.UUID   `json:"space_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.SpaceID, arg.ParentID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFolderAncestors = `-- name: GetFolderAncestors :many
WITH RECURSIVE ancestors AS (
    SELECT f.id, f.space_id, f.parent_id, f.name, 0 AS depth
    FROM folders f WHERE f.id = $1
    UNION ALL
    SELECT f.id, f.space_id, f.parent_id, f.name, a.depth + 1
    FROM folders f
    JOIN ancestors a ON f.id = a.parent_id
)
SELECT ancestors.id, ancestors.name, ancestors.depth FROM ancestors ORDER BY ancestors.depth DESC
`

type GetFolderAncestorsRow struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Depth int32     `json:"depth"`
}

func (q *Queries) GetFolderAncestors(ctx context.Context, id uuid.UUID) ([]GetFolderAncestorsRow, error) {
	rows, err := q.db.Query(ctx, getFolderAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFolderAncestorsRow{}
	for rows.Next() {
		var i GetFolderAncestorsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Depth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, space_id, parent_id, name, created_at, updated_at, deleted_at FROM folders WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFolderByID(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFoldersByParent = `-- name: ListFoldersByParent :many
SELECT id, space_id, parent_id, name, created_at, updated_at, deleted_at FROM folders
WHERE space_id = $1 AND parent_id = $2 AND deleted_at IS NULL
ORDER BY name
`

type ListFoldersByParentParams struct {
	SpaceID  uuid.UUID   `json:"space_id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) ListFoldersByParent(ctx context.Context, arg ListFoldersByParentParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByParent, arg.SpaceID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFolders = `-- name: ListRootFolders :many
SELECT id, space_id, parent_id, name, created_at, updated_at, deleted_at FROM folders
WHERE space_id = $1 AND parent_id IS NULL AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListRootFolders(ctx context.Context, spaceID uuid.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listRootFolders, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFolder = `-- name: MoveFolder :exec
UPDATE folders SET parent_id = $2, updated_at = now() WHERE id = $1
`

type MoveFolderParams struct {
	ID       uuid.UUID   `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) MoveFolder(ctx context.Context, arg MoveFolderParams) error {
	_, err := q.db.Exec(ctx, moveFolder, arg.ID, arg.ParentID)
	return err
}

const renameFolder = `-- name: RenameFolder :exec
UPDATE folders SET name = $2, updated_at = now() WHERE id = $1
`

type RenameFolderParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) error {
	_, err := q.db.Exec(ctx, renameFolder, arg.ID, arg.Name)
	return err
}

const restoreFolder = `-- name: RestoreFolder :exec
UPDATE folders SET deleted_at = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) RestoreFolder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreFolder, id)
	return err
}

const softDeleteFolder = `-- name: SoftDeleteFolder :exec
UPDATE folders SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteFolder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFolder, id)
	return err
}
