// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE invitations
SET status = 'accepted', updated_at = now()
WHERE id = $1
`

func (q *Queries) AcceptInvitation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, acceptInvitation, id)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (space_id, email, role, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, space_id, email, role, status, invited_by, expires_at, created_at, updated_at
`

type CreateInvitationParams struct {
	SpaceID   uuid.UUID      `json:"space_id"`
	Email     string         `json:"email"`
	Role      MembershipRole `json:"role"`
	InvitedBy int64          `json:"invited_by"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.SpaceID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expirePendingInvitations = `-- name: ExpirePendingInvitations :exec
UPDATE invitations
SET status = 'expired', updated_at = now()
WHERE status = 'pending' AND expires_at < now()
`

func (q *Queries) ExpirePendingInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expirePendingInvitations)
	return err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, space_id, email, role, status, invited_by, expires_at, created_at, updated_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id int64) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingInvitationsByEmail = `-- name: ListPendingInvitationsByEmail :many
SELECT id, space_id, email, role, status, invited_by, expires_at, created_at, updated_at FROM invitations
WHERE email = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitationsByEmail(ctx context.Context, email string) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsBySpace = `-- name: ListPendingInvitationsBySpace :many
SELECT id, space_id, email, role, status, invited_by, expires_at, created_at, updated_at FROM invitations
WHERE space_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitationsBySpace(ctx context.Context, spaceID uuid.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :exec
UPDATE invitations
SET status = 'revoked', updated_at = now()
WHERE id = $1
`

func (q *Queries) RevokeInvitation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeInvitation, id)
	return err
}
