// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextArchiveJob = `-- name: ClaimNextArchiveJob :one
UPDATE archive_sync_jobs
SET status = 'processing', attempts = attempts + 1, updated_at = now()
WHERE id = (
    SELECT id FROM archive_sync_jobs
    WHERE status IN ('pending', 'failed')
      AND attempts < max_attempts
      AND (next_retry_at IS NULL OR next_retry_at <= now())
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, asset_id, status, attempts, max_attempts, last_error, next_retry_at, completed_at, created_at, updated_at
`

func (q *Queries) ClaimNextArchiveJob(ctx context.Context) (ArchiveSyncJob, error) {
	row := q.db.QueryRow(ctx, claimNextArchiveJob)
	var i ArchiveSyncJob
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeArchiveJob = `-- name: CompleteArchiveJob :exec
UPDATE archive_sync_jobs
SET status = 'completed', completed_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) CompleteArchiveJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeArchiveJob, id)
	return err
}

const createArchiveSyncJob = `-- name: CreateArchiveSyncJob :one
INSERT INTO archive_sync_jobs (asset_id)
VALUES ($1)
RETURNING id, asset_id, status, attempts, max_attempts, last_error, next_retry_at, completed_at, created_at, updated_at
`

func (q *Queries) CreateArchiveSyncJob(ctx context.Context, assetID uuid.UUID) (ArchiveSyncJob, error) {
	row := q.db.QueryRow(ctx, createArchiveSyncJob, assetID)
	var i ArchiveSyncJob
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failArchiveJob = `-- name: FailArchiveJob :exec
UPDATE archive_sync_jobs
SET status = 'failed', last_error = $2, next_retry_at = $3, updated_at = now()
WHERE id = $1
`

type FailArchiveJobParams struct {
	ID          int64              `json:"id"`
	LastError   *string            `json:"last_error"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) FailArchiveJob(ctx context.Context, arg FailArchiveJobParams) error {
	_, err := q.db.Exec(ctx, failArchiveJob, arg.ID, arg.LastError, arg.NextRetryAt)
	return err
}

const listPendingArchiveJobs = `-- name: ListPendingArchiveJobs :many
SELECT id, asset_id, status, attempts, max_attempts, last_error, next_retry_at, completed_at, created_at, updated_at FROM archive_sync_jobs
WHERE status IN ('pending', 'failed') AND attempts < max_attempts
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListPendingArchiveJobs(ctx context.Context, limit int32) ([]ArchiveSyncJob, error) {
	rows, err := q.db.Query(ctx, listPendingArchiveJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchiveSyncJob{}
	for rows.Next() {
		var i ArchiveSyncJob
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.NextRetryAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
