// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ClientType string

const (
	ClientTypeWeb ClientType = "web"
	ClientTypeCli ClientType = "cli"
)

func (e *ClientType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClientType(s)
	case string:
		*e = ClientType(s)
	default:
		return fmt.Errorf("unsupported scan type for ClientType: %T", src)
	}
	return nil
}

type NullClientType struct {
	ClientType ClientType `json:"client_type"`
	Valid      bool       `json:"valid"` // Valid is true if ClientType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClientType) Scan(value interface{}) error {
	if value == nil {
		ns.ClientType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClientType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClientType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClientType), nil
}

type InvitationStatus string

const (
	InvitationStatusPending  InvitationStatus = "pending"
	InvitationStatusAccepted InvitationStatus = "accepted"
	InvitationStatusExpired  InvitationStatus = "expired"
	InvitationStatusRevoked  InvitationStatus = "revoked"
)

func (e *InvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationStatus(s)
	case string:
		*e = InvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationStatus: %T", src)
	}
	return nil
}

type NullInvitationStatus struct {
	InvitationStatus InvitationStatus `json:"invitation_status"`
	Valid            bool             `json:"valid"` // Valid is true if InvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationStatus), nil
}

type LocationStatus string

const (
	LocationStatusPending LocationStatus = "pending"
	LocationStatusStored  LocationStatus = "stored"
	LocationStatusFailed  LocationStatus = "failed"
)

func (e *LocationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocationStatus(s)
	case string:
		*e = LocationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LocationStatus: %T", src)
	}
	return nil
}

type NullLocationStatus struct {
	LocationStatus LocationStatus `json:"location_status"`
	Valid          bool           `json:"valid"` // Valid is true if LocationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LocationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocationStatus), nil
}

type MembershipRole string

const (
	MembershipRoleOwner  MembershipRole = "owner"
	MembershipRoleEditor MembershipRole = "editor"
	MembershipRoleViewer MembershipRole = "viewer"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole `json:"membership_role"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type StorageLayer string

const (
	StorageLayerServing StorageLayer = "serving"
	StorageLayerArchive StorageLayer = "archive"
)

func (e *StorageLayer) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StorageLayer(s)
	case string:
		*e = StorageLayer(s)
	default:
		return fmt.Errorf("unsupported scan type for StorageLayer: %T", src)
	}
	return nil
}

type NullStorageLayer struct {
	StorageLayer StorageLayer `json:"storage_layer"`
	Valid        bool         `json:"valid"` // Valid is true if StorageLayer is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStorageLayer) Scan(value interface{}) error {
	if value == nil {
		ns.StorageLayer, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StorageLayer.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStorageLayer) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StorageLayer), nil
}

type StorageProvider string

const (
	StorageProviderCloudinary StorageProvider = "cloudinary"
	StorageProviderImagekit   StorageProvider = "imagekit"
	StorageProviderR2         StorageProvider = "r2"
	StorageProviderGcs        StorageProvider = "gcs"
)

func (e *StorageProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StorageProvider(s)
	case string:
		*e = StorageProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for StorageProvider: %T", src)
	}
	return nil
}

type NullStorageProvider struct {
	StorageProvider StorageProvider `json:"storage_provider"`
	Valid           bool            `json:"valid"` // Valid is true if StorageProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStorageProvider) Scan(value interface{}) error {
	if value == nil {
		ns.StorageProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StorageProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStorageProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StorageProvider), nil
}

type ArchiveSyncJob struct {
	ID          int64              `json:"id"`
	AssetID     uuid.UUID          `json:"asset_id"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	LastError   *string            `json:"last_error"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type Asset struct {
	ID               uuid.UUID `json:"id"`
	OriginalFilename string    `json:"original_filename"`
	Name             string    `json:"name"`
	MimeType         string    `json:"mime_type"`
	SizeBytes        int64     `json:"size_bytes"`
	ChecksumSha256   string    `json:"checksum_sha256"`
	Width            *int32    `json:"width"`
	Height           *int32    `json:"height"`
	UploadedBy       int64     `json:"uploaded_by"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type AssetReference struct {
	ID        int64              `json:"id"`
	AssetID   uuid.UUID          `json:"asset_id"`
	SpaceID   uuid.UUID          `json:"space_id"`
	FolderID  pgtype.UUID        `json:"folder_id"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type AssetTag struct {
	AssetID uuid.UUID `json:"asset_id"`
	TagID   int64     `json:"tag_id"`
}

type Folder struct {
	ID        uuid.UUID          `json:"id"`
	SpaceID   uuid.UUID          `json:"space_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Name      string             `json:"name"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Invitation struct {
	ID        int64            `json:"id"`
	SpaceID   uuid.UUID        `json:"space_id"`
	Email     string           `json:"email"`
	Role      MembershipRole   `json:"role"`
	Status    InvitationStatus `json:"status"`
	TokenHash string           `json:"token_hash"`
	InvitedBy int64            `json:"invited_by"`
	ExpiresAt time.Time        `json:"expires_at"`
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
}

type Session struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	Client     ClientType         `json:"client"`
	Label      string             `json:"label"`
	LastUsedAt time.Time          `json:"last_used_at"`
	ExpiresAt  time.Time          `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type Space struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	OwnerID           int64     `json:"owner_id"`
	StorageQuotaBytes int64     `json:"storage_quota_bytes"`
	StorageUsedBytes  int64     `json:"storage_used_bytes"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type SpaceMember struct {
	ID       int64          `json:"id"`
	SpaceID  uuid.UUID      `json:"space_id"`
	UserID   int64          `json:"user_id"`
	Role     MembershipRole `json:"role"`
	JoinedAt time.Time      `json:"joined_at"`
}

type StorageAccount struct {
	ID                   int64           `json:"id"`
	Provider             StorageProvider `json:"provider"`
	Label                string          `json:"label"`
	Layer                StorageLayer    `json:"layer"`
	CredentialsEncrypted []byte          `json:"credentials_encrypted"`
	IsActive             bool            `json:"is_active"`
	QuotaBytes           int64           `json:"quota_bytes"`
	UsedBytes            int64           `json:"used_bytes"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

type StorageLocation struct {
	ID         int64          `json:"id"`
	AssetID    uuid.UUID      `json:"asset_id"`
	AccountID  int64          `json:"account_id"`
	Layer      StorageLayer   `json:"layer"`
	Status     LocationStatus `json:"status"`
	RemotePath *string        `json:"remote_path"`
	RemoteUrl  *string        `json:"remote_url"`
	Error      *string        `json:"error"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Tag struct {
	ID        int64     `json:"id"`
	SpaceID   uuid.UUID `json:"space_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	AvatarUrl    *string   `json:"avatar_url"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type UserRole struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	RoleName  string    `json:"role_name"`
	CreatedAt time.Time `json:"created_at"`
}
