// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"
)

const createCLISession = `-- name: CreateCLISession :one
INSERT INTO cli_sessions (user_id, token_hash, label, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, label, last_used_at, expires_at, revoked_at, created_at
`

type CreateCLISessionParams struct {
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	Label     string    `json:"label"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateCLISession(ctx context.Context, arg CreateCLISessionParams) (CliSession, error) {
	row := q.db.QueryRow(ctx, createCLISession,
		arg.UserID,
		arg.TokenHash,
		arg.Label,
		arg.ExpiresAt,
	)
	var i CliSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Label,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, label, last_used_at, expires_at, revoked_at, created_at FROM cli_sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (CliSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i CliSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Label,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, user_id, token_hash, label, last_used_at, expires_at, revoked_at, created_at FROM cli_sessions
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY last_used_at DESC
`

func (q *Queries) ListActiveSessions(ctx context.Context, userID int64) ([]CliSession, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CliSession{}
	for rows.Next() {
		var i CliSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Label,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE cli_sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE cli_sessions SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE cli_sessions SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
