// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spaces.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addSpaceMember = `-- name: AddSpaceMember :one
INSERT INTO space_members (space_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, space_id, user_id, role, joined_at
`

type AddSpaceMemberParams struct {
	SpaceID uuid.UUID      `json:"space_id"`
	UserID  int64          `json:"user_id"`
	Role    MembershipRole `json:"role"`
}

func (q *Queries) AddSpaceMember(ctx context.Context, arg AddSpaceMemberParams) (SpaceMember, error) {
	row := q.db.QueryRow(ctx, addSpaceMember, arg.SpaceID, arg.UserID, arg.Role)
	var i SpaceMember
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (name, owner_id, storage_quota_bytes)
VALUES ($1, $2, $3)
RETURNING id, name, owner_id, storage_quota_bytes, storage_used_bytes, created_at, updated_at
`

type CreateSpaceParams struct {
	Name              string `json:"name"`
	OwnerID           int64  `json:"owner_id"`
	StorageQuotaBytes int64  `json:"storage_quota_bytes"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace, arg.Name, arg.OwnerID, arg.StorageQuotaBytes)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.StorageQuotaBytes,
		&i.StorageUsedBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementSpaceUsage = `-- name: DecrementSpaceUsage :exec
UPDATE spaces
SET storage_used_bytes = GREATEST(storage_used_bytes - $2, 0), updated_at = now()
WHERE id = $1
`

type DecrementSpaceUsageParams struct {
	ID               uuid.UUID `json:"id"`
	StorageUsedBytes int64     `json:"storage_used_bytes"`
}

func (q *Queries) DecrementSpaceUsage(ctx context.Context, arg DecrementSpaceUsageParams) error {
	_, err := q.db.Exec(ctx, decrementSpaceUsage, arg.ID, arg.StorageUsedBytes)
	return err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpace, id)
	return err
}

const getSpaceByID = `-- name: GetSpaceByID :one
SELECT id, name, owner_id, storage_quota_bytes, storage_used_bytes, created_at, updated_at FROM spaces WHERE id = $1
`

func (q *Queries) GetSpaceByID(ctx context.Context, id uuid.UUID) (Space, error) {
	row := q.db.QueryRow(ctx, getSpaceByID, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.StorageQuotaBytes,
		&i.StorageUsedBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpaceMember = `-- name: GetSpaceMember :one
SELECT id, space_id, user_id, role, joined_at FROM space_members WHERE space_id = $1 AND user_id = $2
`

type GetSpaceMemberParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	UserID  int64     `json:"user_id"`
}

func (q *Queries) GetSpaceMember(ctx context.Context, arg GetSpaceMemberParams) (SpaceMember, error) {
	row := q.db.QueryRow(ctx, getSpaceMember, arg.SpaceID, arg.UserID)
	var i SpaceMember
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const incrementSpaceUsage = `-- name: IncrementSpaceUsage :exec
UPDATE spaces
SET storage_used_bytes = storage_used_bytes + $2, updated_at = now()
WHERE id = $1
`

type IncrementSpaceUsageParams struct {
	ID               uuid.UUID `json:"id"`
	StorageUsedBytes int64     `json:"storage_used_bytes"`
}

func (q *Queries) IncrementSpaceUsage(ctx context.Context, arg IncrementSpaceUsageParams) error {
	_, err := q.db.Exec(ctx, incrementSpaceUsage, arg.ID, arg.StorageUsedBytes)
	return err
}

const listSpaceMembers = `-- name: ListSpaceMembers :many
SELECT sm.id, sm.space_id, sm.user_id, sm.role, sm.joined_at, u.email, u.name, u.avatar_url
FROM space_members sm
JOIN users u ON u.id = sm.user_id
WHERE sm.space_id = $1
ORDER BY sm.joined_at
`

type ListSpaceMembersRow struct {
	ID        int64          `json:"id"`
	SpaceID   uuid.UUID      `json:"space_id"`
	UserID    int64          `json:"user_id"`
	Role      MembershipRole `json:"role"`
	JoinedAt  time.Time      `json:"joined_at"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	AvatarUrl *string        `json:"avatar_url"`
}

func (q *Queries) ListSpaceMembers(ctx context.Context, spaceID uuid.UUID) ([]ListSpaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listSpaceMembers, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpaceMembersRow{}
	for rows.Next() {
		var i ListSpaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesByMember = `-- name: ListSpacesByMember :many
SELECT s.id, s.name, s.owner_id, s.storage_quota_bytes, s.storage_used_bytes, s.created_at, s.updated_at FROM spaces s
JOIN space_members sm ON sm.space_id = s.id
WHERE sm.user_id = $1
ORDER BY s.created_at
`

func (q *Queries) ListSpacesByMember(ctx context.Context, userID int64) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpacesByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.StorageQuotaBytes,
			&i.StorageUsedBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesByOwner = `-- name: ListSpacesByOwner :many
SELECT id, name, owner_id, storage_quota_bytes, storage_used_bytes, created_at, updated_at FROM spaces WHERE owner_id = $1 ORDER BY created_at
`

func (q *Queries) ListSpacesByOwner(ctx context.Context, ownerID int64) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpacesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.StorageQuotaBytes,
			&i.StorageUsedBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSpaceMember = `-- name: RemoveSpaceMember :exec
DELETE FROM space_members WHERE space_id = $1 AND user_id = $2
`

type RemoveSpaceMemberParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	UserID  int64     `json:"user_id"`
}

func (q *Queries) RemoveSpaceMember(ctx context.Context, arg RemoveSpaceMemberParams) error {
	_, err := q.db.Exec(ctx, removeSpaceMember, arg.SpaceID, arg.UserID)
	return err
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE spaces
SET name = $2, storage_quota_bytes = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, owner_id, storage_quota_bytes, storage_used_bytes, created_at, updated_at
`

type UpdateSpaceParams struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	StorageQuotaBytes int64     `json:"storage_quota_bytes"`
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, updateSpace, arg.ID, arg.Name, arg.StorageQuotaBytes)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.StorageQuotaBytes,
		&i.StorageUsedBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSpaceMemberRole = `-- name: UpdateSpaceMemberRole :exec
UPDATE space_members SET role = $3 WHERE space_id = $1 AND user_id = $2
`

type UpdateSpaceMemberRoleParams struct {
	SpaceID uuid.UUID      `json:"space_id"`
	UserID  int64          `json:"user_id"`
	Role    MembershipRole `json:"role"`
}

func (q *Queries) UpdateSpaceMemberRole(ctx context.Context, arg UpdateSpaceMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateSpaceMemberRole, arg.SpaceID, arg.UserID, arg.Role)
	return err
}
