// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStorageAccount = `-- name: CreateStorageAccount :one
INSERT INTO storage_accounts (provider, label, layer, credentials_encrypted, quota_bytes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, provider, label, layer, credentials_encrypted, is_active, quota_bytes, used_bytes, created_at, updated_at
`

type CreateStorageAccountParams struct {
	Provider             StorageProvider `json:"provider"`
	Label                string          `json:"label"`
	Layer                StorageLayer    `json:"layer"`
	CredentialsEncrypted []byte          `json:"credentials_encrypted"`
	QuotaBytes           int64           `json:"quota_bytes"`
}

func (q *Queries) CreateStorageAccount(ctx context.Context, arg CreateStorageAccountParams) (StorageAccount, error) {
	row := q.db.QueryRow(ctx, createStorageAccount,
		arg.Provider,
		arg.Label,
		arg.Layer,
		arg.CredentialsEncrypted,
		arg.QuotaBytes,
	)
	var i StorageAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Label,
		&i.Layer,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStorageLocation = `-- name: CreateStorageLocation :one
INSERT INTO storage_locations (asset_id, account_id, layer, status, remote_path, remote_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, asset_id, account_id, layer, status, remote_path, remote_url, error, created_at, updated_at
`

type CreateStorageLocationParams struct {
	AssetID    uuid.UUID      `json:"asset_id"`
	AccountID  int64          `json:"account_id"`
	Layer      StorageLayer   `json:"layer"`
	Status     LocationStatus `json:"status"`
	RemotePath *string        `json:"remote_path"`
	RemoteUrl  *string        `json:"remote_url"`
}

func (q *Queries) CreateStorageLocation(ctx context.Context, arg CreateStorageLocationParams) (StorageLocation, error) {
	row := q.db.QueryRow(ctx, createStorageLocation,
		arg.AssetID,
		arg.AccountID,
		arg.Layer,
		arg.Status,
		arg.RemotePath,
		arg.RemoteUrl,
	)
	var i StorageLocation
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.AccountID,
		&i.Layer,
		&i.Status,
		&i.RemotePath,
		&i.RemoteUrl,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAccount = `-- name: DeactivateAccount :exec
UPDATE storage_accounts SET is_active = false, updated_at = now() WHERE id = $1
`

func (q *Queries) DeactivateAccount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateAccount, id)
	return err
}

const decrementAccountUsage = `-- name: DecrementAccountUsage :exec
UPDATE storage_accounts
SET used_bytes = GREATEST(used_bytes - $2, 0), updated_at = now()
WHERE id = $1
`

type DecrementAccountUsageParams struct {
	ID        int64 `json:"id"`
	UsedBytes int64 `json:"used_bytes"`
}

func (q *Queries) DecrementAccountUsage(ctx context.Context, arg DecrementAccountUsageParams) error {
	_, err := q.db.Exec(ctx, decrementAccountUsage, arg.ID, arg.UsedBytes)
	return err
}

const getArchiveLocation = `-- name: GetArchiveLocation :one
SELECT id, asset_id, account_id, layer, status, remote_path, remote_url, error, created_at, updated_at FROM storage_locations
WHERE asset_id = $1 AND layer = 'archive' AND status = 'stored'
LIMIT 1
`

func (q *Queries) GetArchiveLocation(ctx context.Context, assetID uuid.UUID) (StorageLocation, error) {
	row := q.db.QueryRow(ctx, getArchiveLocation, assetID)
	var i StorageLocation
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.AccountID,
		&i.Layer,
		&i.Status,
		&i.RemotePath,
		&i.RemoteUrl,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServingLocation = `-- name: GetServingLocation :one
SELECT id, asset_id, account_id, layer, status, remote_path, remote_url, error, created_at, updated_at FROM storage_locations
WHERE asset_id = $1 AND layer = 'serving' AND status = 'stored'
LIMIT 1
`

func (q *Queries) GetServingLocation(ctx context.Context, assetID uuid.UUID) (StorageLocation, error) {
	row := q.db.QueryRow(ctx, getServingLocation, assetID)
	var i StorageLocation
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.AccountID,
		&i.Layer,
		&i.Status,
		&i.RemotePath,
		&i.RemoteUrl,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageAccountByID = `-- name: GetStorageAccountByID :one
SELECT id, provider, label, layer, credentials_encrypted, is_active, quota_bytes, used_bytes, created_at, updated_at FROM storage_accounts WHERE id = $1
`

func (q *Queries) GetStorageAccountByID(ctx context.Context, id int64) (StorageAccount, error) {
	row := q.db.QueryRow(ctx, getStorageAccountByID, id)
	var i StorageAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Label,
		&i.Layer,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAccountUsage = `-- name: IncrementAccountUsage :exec
UPDATE storage_accounts
SET used_bytes = used_bytes + $2, updated_at = now()
WHERE id = $1
`

type IncrementAccountUsageParams struct {
	ID        int64 `json:"id"`
	UsedBytes int64 `json:"used_bytes"`
}

func (q *Queries) IncrementAccountUsage(ctx context.Context, arg IncrementAccountUsageParams) error {
	_, err := q.db.Exec(ctx, incrementAccountUsage, arg.ID, arg.UsedBytes)
	return err
}

const listActiveAccountsByLayer = `-- name: ListActiveAccountsByLayer :many
SELECT id, provider, label, layer, credentials_encrypted, is_active, quota_bytes, used_bytes, created_at, updated_at FROM storage_accounts
WHERE layer = $1 AND is_active = true
ORDER BY used_bytes ASC
`

func (q *Queries) ListActiveAccountsByLayer(ctx context.Context, layer StorageLayer) ([]StorageAccount, error) {
	rows, err := q.db.Query(ctx, listActiveAccountsByLayer, layer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageAccount{}
	for rows.Next() {
		var i StorageAccount
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Label,
			&i.Layer,
			&i.CredentialsEncrypted,
			&i.IsActive,
			&i.QuotaBytes,
			&i.UsedBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllStorageAccounts = `-- name: ListAllStorageAccounts :many
SELECT id, provider, label, layer, credentials_encrypted, is_active, quota_bytes, used_bytes, created_at, updated_at FROM storage_accounts ORDER BY created_at
`

func (q *Queries) ListAllStorageAccounts(ctx context.Context) ([]StorageAccount, error) {
	rows, err := q.db.Query(ctx, listAllStorageAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageAccount{}
	for rows.Next() {
		var i StorageAccount
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Label,
			&i.Layer,
			&i.CredentialsEncrypted,
			&i.IsActive,
			&i.QuotaBytes,
			&i.UsedBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByAsset = `-- name: ListLocationsByAsset :many
SELECT id, asset_id, account_id, layer, status, remote_path, remote_url, error, created_at, updated_at FROM storage_locations WHERE asset_id = $1 ORDER BY created_at
`

func (q *Queries) ListLocationsByAsset(ctx context.Context, assetID uuid.UUID) ([]StorageLocation, error) {
	rows, err := q.db.Query(ctx, listLocationsByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageLocation{}
	for rows.Next() {
		var i StorageLocation
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.AccountID,
			&i.Layer,
			&i.Status,
			&i.RemotePath,
			&i.RemoteUrl,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStorageAccount = `-- name: UpdateStorageAccount :exec
UPDATE storage_accounts
SET label = $2, is_active = $3, quota_bytes = $4, updated_at = now()
WHERE id = $1
`

type UpdateStorageAccountParams struct {
	ID         int64  `json:"id"`
	Label      string `json:"label"`
	IsActive   bool   `json:"is_active"`
	QuotaBytes int64  `json:"quota_bytes"`
}

func (q *Queries) UpdateStorageAccount(ctx context.Context, arg UpdateStorageAccountParams) error {
	_, err := q.db.Exec(ctx, updateStorageAccount,
		arg.ID,
		arg.Label,
		arg.IsActive,
		arg.QuotaBytes,
	)
	return err
}

const updateStorageLocationStatus = `-- name: UpdateStorageLocationStatus :exec
UPDATE storage_locations
SET status = $2, remote_path = $3, remote_url = $4, error = $5, updated_at = now()
WHERE id = $1
`

type UpdateStorageLocationStatusParams struct {
	ID         int64          `json:"id"`
	Status     LocationStatus `json:"status"`
	RemotePath *string        `json:"remote_path"`
	RemoteUrl  *string        `json:"remote_url"`
	Error      *string        `json:"error"`
}

func (q *Queries) UpdateStorageLocationStatus(ctx context.Context, arg UpdateStorageLocationStatusParams) error {
	_, err := q.db.Exec(ctx, updateStorageLocationStatus,
		arg.ID,
		arg.Status,
		arg.RemotePath,
		arg.RemoteUrl,
		arg.Error,
	)
	return err
}
