// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addAssetTag = `-- name: AddAssetTag :exec
INSERT INTO asset_tags (asset_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddAssetTagParams struct {
	AssetID uuid.UUID `json:"asset_id"`
	TagID   int64     `json:"tag_id"`
}

func (q *Queries) AddAssetTag(ctx context.Context, arg AddAssetTagParams) error {
	_, err := q.db.Exec(ctx, addAssetTag, arg.AssetID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (space_id, name)
VALUES ($1, $2)
RETURNING id, space_id, name, created_at
`

type CreateTagParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	Name    string    `json:"name"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.SpaceID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, space_id, name, created_at FROM tags WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, space_id, name, created_at FROM tags WHERE space_id = $1 AND name = $2
`

type GetTagByNameParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	Name    string    `json:"name"`
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, arg.SpaceID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listAssetsByTag = `-- name: ListAssetsByTag :many
SELECT a.id, a.original_filename, a.name, a.mime_type, a.size_bytes, a.checksum_sha256, a.width, a.height, a.uploaded_by, a.created_at, a.updated_at FROM assets a
JOIN asset_tags at ON at.asset_id = a.id
WHERE at.tag_id = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAssetsByTagParams struct {
	TagID  int64 `json:"tag_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAssetsByTag(ctx context.Context, arg ListAssetsByTagParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByTag, arg.TagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.Name,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.Width,
			&i.Height,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByAsset = `-- name: ListTagsByAsset :many
SELECT t.id, t.space_id, t.name, t.created_at FROM tags t
JOIN asset_tags at ON at.tag_id = t.id
WHERE at.asset_id = $1
ORDER BY t.name
`

func (q *Queries) ListTagsByAsset(ctx context.Context, assetID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsBySpace = `-- name: ListTagsBySpace :many
SELECT id, space_id, name, created_at FROM tags WHERE space_id = $1 ORDER BY name
`

func (q *Queries) ListTagsBySpace(ctx context.Context, spaceID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAssetTag = `-- name: RemoveAssetTag :exec
DELETE FROM asset_tags WHERE asset_id = $1 AND tag_id = $2
`

type RemoveAssetTagParams struct {
	AssetID uuid.UUID `json:"asset_id"`
	TagID   int64     `json:"tag_id"`
}

func (q *Queries) RemoveAssetTag(ctx context.Context, arg RemoveAssetTagParams) error {
	_, err := q.db.Exec(ctx, removeAssetTag, arg.AssetID, arg.TagID)
	return err
}
