// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (clerk_user_id, email, name, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, clerk_user_id, email, name, avatar_url, is_active, last_seen_at, created_at, updated_at
`

type CreateUserParams struct {
	ClerkUserID string  `json:"clerk_user_id"`
	Email       string  `json:"email"`
	Name        string  `json:"name"`
	AvatarUrl   *string `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ClerkUserID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUserByClerkID = `-- name: DeactivateUserByClerkID :exec
UPDATE users
SET is_active = FALSE
WHERE clerk_user_id = $1
`

func (q *Queries) DeactivateUserByClerkID(ctx context.Context, clerkUserID string) error {
	_, err := q.db.Exec(ctx, deactivateUserByClerkID, clerkUserID)
	return err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_user_id, email, name, avatar_url, is_active, last_seen_at, created_at, updated_at FROM users
WHERE clerk_user_id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, clerk_user_id, email, name, avatar_url, is_active, last_seen_at, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, clerk_user_id, email, name, avatar_url, is_active, last_seen_at, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchUserLastSeen = `-- name: TouchUserLastSeen :exec
UPDATE users
SET last_seen_at = now()
WHERE id = $1
`

func (q *Queries) TouchUserLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchUserLastSeen, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name = $2,
    avatar_url = $3
WHERE id = $1
RETURNING id, clerk_user_id, email, name, avatar_url, is_active, last_seen_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByClerkID = `-- name: UpsertUserByClerkID :one
INSERT INTO users (clerk_user_id, email, name, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (clerk_user_id) DO UPDATE
SET email = EXCLUDED.email,
    name = EXCLUDED.name,
    avatar_url = EXCLUDED.avatar_url,
    is_active = TRUE
RETURNING id, clerk_user_id, email, name, avatar_url, is_active, last_seen_at, created_at, updated_at
`

type UpsertUserByClerkIDParams struct {
	ClerkUserID string  `json:"clerk_user_id"`
	Email       string  `json:"email"`
	Name        string  `json:"name"`
	AvatarUrl   *string `json:"avatar_url"`
}

func (q *Queries) UpsertUserByClerkID(ctx context.Context, arg UpsertUserByClerkIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByClerkID,
		arg.ClerkUserID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
