// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    name,
    password_hash
) VALUES (
    $1, $2, $3
) RETURNING id, email, name, password_hash, storage_quota, storage_used, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, storage_quota, storage_used, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, storage_quota, storage_used, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserQuota = `-- name: GetUserQuota :one
SELECT storage_quota, storage_used
FROM users
WHERE id = $1
`

type GetUserQuotaRow struct {
	StorageQuota int64 `json:"storage_quota"`
	StorageUsed  int64 `json:"storage_used"`
}

func (q *Queries) GetUserQuota(ctx context.Context, id pgtype.UUID) (GetUserQuotaRow, error) {
	row := q.db.QueryRow(ctx, getUserQuota, id)
	var i GetUserQuotaRow
	err := row.Scan(&i.StorageQuota, &i.StorageUsed)
	return i, err
}

const updateUserStorageUsed = `-- name: UpdateUserStorageUsed :one
UPDATE users
SET storage_used = $2
WHERE id = $1
RETURNING id, email, name, password_hash, storage_quota, storage_used, created_at, updated_at
`

type UpdateUserStorageUsedParams struct {
	ID          pgtype.UUID `json:"id"`
	StorageUsed int64       `json:"storage_used"`
}

func (q *Queries) UpdateUserStorageUsed(ctx context.Context, arg UpdateUserStorageUsedParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStorageUsed, arg.ID, arg.StorageUsed)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
