// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albums.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAssetToAlbum = `-- name: AddAssetToAlbum :exec
INSERT INTO album_assets (album_id, asset_id, added_by, sort_order)
VALUES ($1, $2, $3, $4)
ON CONFLICT (album_id, asset_id) DO NOTHING
`

type AddAssetToAlbumParams struct {
	AlbumID   int64     `json:"album_id"`
	AssetID   uuid.UUID `json:"asset_id"`
	AddedBy   *int64    `json:"added_by"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) AddAssetToAlbum(ctx context.Context, arg AddAssetToAlbumParams) error {
	_, err := q.db.Exec(ctx, addAssetToAlbum,
		arg.AlbumID,
		arg.AssetID,
		arg.AddedBy,
		arg.SortOrder,
	)
	return err
}

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (gallery_id, owner_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, gallery_id, owner_id, name, description, cover_asset_id, created_at, updated_at
`

type CreateAlbumParams struct {
	GalleryID   int64   `json:"gallery_id"`
	OwnerID     int64   `json:"owner_id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.GalleryID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CoverAssetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM albums WHERE id = $1
`

func (q *Queries) DeleteAlbum(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAlbum, id)
	return err
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, gallery_id, owner_id, name, description, cover_asset_id, created_at, updated_at FROM albums WHERE id = $1
`

func (q *Queries) GetAlbumByID(ctx context.Context, id int64) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByID, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CoverAssetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlbumMember = `-- name: GetAlbumMember :one
SELECT album_id, user_id, role, invited_by, created_at FROM album_members WHERE album_id = $1 AND user_id = $2
`

type GetAlbumMemberParams struct {
	AlbumID int64 `json:"album_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) GetAlbumMember(ctx context.Context, arg GetAlbumMemberParams) (AlbumMember, error) {
	row := q.db.QueryRow(ctx, getAlbumMember, arg.AlbumID, arg.UserID)
	var i AlbumMember
	err := row.Scan(
		&i.AlbumID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAlbumAssetIDs = `-- name: ListAlbumAssetIDs :many
SELECT asset_id FROM album_assets
WHERE album_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListAlbumAssetIDs(ctx context.Context, albumID int64) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAlbumAssetIDs, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var asset_id uuid.UUID
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumMembers = `-- name: ListAlbumMembers :many
SELECT am.album_id, am.user_id, am.role, am.created_at,
       u.email, u.name, u.avatar_url
FROM album_members am
JOIN users u ON u.id = am.user_id
WHERE am.album_id = $1
ORDER BY am.created_at
`

type ListAlbumMembersRow struct {
	AlbumID   int64      `json:"album_id"`
	UserID    int64      `json:"user_id"`
	Role      MemberRole `json:"role"`
	CreatedAt time.Time  `json:"created_at"`
	Email     string     `json:"email"`
	Name      string     `json:"name"`
	AvatarUrl *string    `json:"avatar_url"`
}

func (q *Queries) ListAlbumMembers(ctx context.Context, albumID int64) ([]ListAlbumMembersRow, error) {
	rows, err := q.db.Query(ctx, listAlbumMembers, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlbumMembersRow{}
	for rows.Next() {
		var i ListAlbumMembersRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByGallery = `-- name: ListAlbumsByGallery :many
SELECT id, gallery_id, owner_id, name, description, cover_asset_id, created_at, updated_at FROM albums WHERE gallery_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAlbumsByGallery(ctx context.Context, galleryID int64) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbumsByGallery, galleryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Album{}
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.GalleryID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.CoverAssetID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAlbumMember = `-- name: RemoveAlbumMember :execrows
DELETE FROM album_members WHERE album_id = $1 AND user_id = $2
`

type RemoveAlbumMemberParams struct {
	AlbumID int64 `json:"album_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) RemoveAlbumMember(ctx context.Context, arg RemoveAlbumMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeAlbumMember, arg.AlbumID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeAssetFromAlbum = `-- name: RemoveAssetFromAlbum :execrows
DELETE FROM album_assets WHERE album_id = $1 AND asset_id = $2
`

type RemoveAssetFromAlbumParams struct {
	AlbumID int64     `json:"album_id"`
	AssetID uuid.UUID `json:"asset_id"`
}

func (q *Queries) RemoveAssetFromAlbum(ctx context.Context, arg RemoveAssetFromAlbumParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeAssetFromAlbum, arg.AlbumID, arg.AssetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAlbum = `-- name: UpdateAlbum :one
UPDATE albums
SET name = $2, description = $3, cover_asset_id = $4
WHERE id = $1
RETURNING id, gallery_id, owner_id, name, description, cover_asset_id, created_at, updated_at
`

type UpdateAlbumParams struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Description  *string     `json:"description"`
	CoverAssetID pgtype.UUID `json:"cover_asset_id"`
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, updateAlbum,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CoverAssetID,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CoverAssetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAlbumMember = `-- name: UpsertAlbumMember :exec
INSERT INTO album_members (album_id, user_id, role, invited_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (album_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertAlbumMemberParams struct {
	AlbumID   int64      `json:"album_id"`
	UserID    int64      `json:"user_id"`
	Role      MemberRole `json:"role"`
	InvitedBy *int64     `json:"invited_by"`
}

func (q *Queries) UpsertAlbumMember(ctx context.Context, arg UpsertAlbumMemberParams) error {
	_, err := q.db.Exec(ctx, upsertAlbumMember,
		arg.AlbumID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	return err
}
