// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countActiveAssetsByGallery = `-- name: CountActiveAssetsByGallery :one
SELECT count(*) FROM assets
WHERE gallery_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountActiveAssetsByGallery(ctx context.Context, galleryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAssetsByGallery, galleryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (gallery_id, uploaded_by, name, type, mime_type, size, hash, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, gallery_id, uploaded_by, name, type, mime_type, size, hash, metadata, deleted_at, deleted_by, created_at, updated_at
`

type CreateAssetParams struct {
	GalleryID  int64  `json:"gallery_id"`
	UploadedBy *int64 `json:"uploaded_by"`
	Name       string `json:"name"`
	Type       string `json:"type"`
	MimeType   string `json:"mime_type"`
	Size       int64  `json:"size"`
	Hash       string `json:"hash"`
	Metadata   []byte `json:"metadata"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.GalleryID,
		arg.UploadedBy,
		arg.Name,
		arg.Type,
		arg.MimeType,
		arg.Size,
		arg.Hash,
		arg.Metadata,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.UploadedBy,
		&i.Name,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.Hash,
		&i.Metadata,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const filterAssetsByType = `-- name: FilterAssetsByType :many
SELECT id, gallery_id, uploaded_by, name, type, mime_type, size, hash, metadata, deleted_at, deleted_by, created_at, updated_at FROM assets
WHERE gallery_id = $1 AND deleted_at IS NULL AND type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type FilterAssetsByTypeParams struct {
	GalleryID int64  `json:"gallery_id"`
	Type      string `json:"type"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) FilterAssetsByType(ctx context.Context, arg FilterAssetsByTypeParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, filterAssetsByType,
		arg.GalleryID,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.GalleryID,
			&i.UploadedBy,
			&i.Name,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.Hash,
			&i.Metadata,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveAssetByGalleryHash = `-- name: GetActiveAssetByGalleryHash :one
SELECT id, gallery_id, uploaded_by, name, type, mime_type, size, hash, metadata, deleted_at, deleted_by, created_at, updated_at FROM assets
WHERE gallery_id = $1 AND hash = $2 AND deleted_at IS NULL
`

type GetActiveAssetByGalleryHashParams struct {
	GalleryID int64  `json:"gallery_id"`
	Hash      string `json:"hash"`
}

func (q *Queries) GetActiveAssetByGalleryHash(ctx context.Context, arg GetActiveAssetByGalleryHashParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getActiveAssetByGalleryHash, arg.GalleryID, arg.Hash)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.UploadedBy,
		&i.Name,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.Hash,
		&i.Metadata,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, gallery_id, uploaded_by, name, type, mime_type, size, hash, metadata, deleted_at, deleted_by, created_at, updated_at FROM assets WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id uuid.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.UploadedBy,
		&i.Name,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.Hash,
		&i.Metadata,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteAsset = `-- name: HardDeleteAsset :exec
DELETE FROM assets WHERE id = $1
`

func (q *Queries) HardDeleteAsset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteAsset, id)
	return err
}

const listActiveAssetsByGallery = `-- name: ListActiveAssetsByGallery :many
SELECT id, gallery_id, uploaded_by, name, type, mime_type, size, hash, metadata, deleted_at, deleted_by, created_at, updated_at FROM assets
WHERE gallery_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveAssetsByGalleryParams struct {
	GalleryID int64 `json:"gallery_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListActiveAssetsByGallery(ctx context.Context, arg ListActiveAssetsByGalleryParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listActiveAssetsByGallery, arg.GalleryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.GalleryID,
			&i.UploadedBy,
			&i.Name,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.Hash,
			&i.Metadata,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedAssetsByGallery = `-- name: ListTrashedAssetsByGallery :many
SELECT id, gallery_id, uploaded_by, name, type, mime_type, size, hash, metadata, deleted_at, deleted_by, created_at, updated_at FROM assets
WHERE gallery_id = $1 AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC
LIMIT $2 OFFSET $3
`

type ListTrashedAssetsByGalleryParams struct {
	GalleryID int64 `json:"gallery_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListTrashedAssetsByGallery(ctx context.Context, arg ListTrashedAssetsByGalleryParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listTrashedAssetsByGallery, arg.GalleryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.GalleryID,
			&i.UploadedBy,
			&i.Name,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.Hash,
			&i.Metadata,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAsset = `-- name: RestoreAsset :execrows
UPDATE assets SET deleted_at = NULL, deleted_by = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreAsset(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreAsset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchAssetsByName = `-- name: SearchAssetsByName :many
SELECT id, gallery_id, uploaded_by, name, type, mime_type, size, hash, metadata, deleted_at, deleted_by, created_at, updated_at FROM assets
WHERE gallery_id = $1 AND deleted_at IS NULL AND name ILIKE $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchAssetsByNameParams struct {
	GalleryID int64  `json:"gallery_id"`
	Name      string `json:"name"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) SearchAssetsByName(ctx context.Context, arg SearchAssetsByNameParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, searchAssetsByName,
		arg.GalleryID,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.GalleryID,
			&i.UploadedBy,
			&i.Name,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.Hash,
			&i.Metadata,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAsset = `-- name: SoftDeleteAsset :execrows
UPDATE assets SET deleted_at = now(), deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteAssetParams struct {
	ID        uuid.UUID `json:"id"`
	DeletedBy *int64    `json:"deleted_by"`
}

func (q *Queries) SoftDeleteAsset(ctx context.Context, arg SoftDeleteAssetParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAsset, arg.ID, arg.DeletedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAssetName = `-- name: UpdateAssetName :one
UPDATE assets SET name = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, gallery_id, uploaded_by, name, type, mime_type, size, hash, metadata, deleted_at, deleted_by, created_at, updated_at
`

type UpdateAssetNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateAssetName(ctx context.Context, arg UpdateAssetNameParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAssetName, arg.ID, arg.Name)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.UploadedBy,
		&i.Name,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.Hash,
		&i.Metadata,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
