// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssetsByUser = `-- name: CountAssetsByUser :one
SELECT COUNT(*) FROM assets
WHERE user_id = $1
`

func (q *Queries) CountAssetsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAssetsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    user_id,
    name,
    type,
    mime_type,
    size,
    hash,
    tags,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, name, type, mime_type, size, hash, tags, metadata, created_at, updated_at
`

type CreateAssetParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Name     string      `json:"name"`
	Type     string      `json:"type"`
	MimeType string      `json:"mime_type"`
	Size     int64       `json:"size"`
	Hash     string      `json:"hash"`
	Tags     []string    `json:"tags"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.MimeType,
		arg.Size,
		arg.Hash,
		arg.Tags,
		arg.Metadata,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.Hash,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets
WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const filterAssetsByType = `-- name: FilterAssetsByType :many
SELECT id, user_id, name, type, mime_type, size, hash, tags, metadata, created_at, updated_at FROM assets
WHERE user_id = $1 AND type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type FilterAssetsByTypeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) FilterAssetsByType(ctx context.Context, arg FilterAssetsByTypeParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, filterAssetsByType,
		arg.UserID,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.Hash,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssetByHash = `-- name: GetAssetByHash :one
SELECT id, user_id, name, type, mime_type, size, hash, tags, metadata, created_at, updated_at FROM assets
WHERE hash = $1 AND user_id = $2
LIMIT 1
`

type GetAssetByHashParams struct {
	Hash   string      `json:"hash"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetAssetByHash(ctx context.Context, arg GetAssetByHashParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByHash, arg.Hash, arg.UserID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.Hash,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, user_id, name, type, mime_type, size, hash, tags, metadata, created_at, updated_at FROM assets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAssetByID(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.Hash,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetsByTypeCount = `-- name: GetAssetsByTypeCount :many
SELECT type, COUNT(*) as count
FROM assets
WHERE user_id = $1
GROUP BY type
ORDER BY count DESC
`

type GetAssetsByTypeCountRow struct {
	Type  string `json:"type"`
	Count int64  `json:"count"`
}

func (q *Queries) GetAssetsByTypeCount(ctx context.Context, userID pgtype.UUID) ([]GetAssetsByTypeCountRow, error) {
	rows, err := q.db.Query(ctx, getAssetsByTypeCount, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssetsByTypeCountRow{}
	for rows.Next() {
		var i GetAssetsByTypeCountRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    COUNT(*) as total_assets,
    COALESCE(SUM(size), 0) as total_size,
    COUNT(DISTINCT type) as unique_types
FROM assets
WHERE user_id = $1
`

type GetDashboardStatsRow struct {
	TotalAssets int64       `json:"total_assets"`
	TotalSize   interface{} `json:"total_size"`
	UniqueTypes int64       `json:"unique_types"`
}

func (q *Queries) GetDashboardStats(ctx context.Context, userID pgtype.UUID) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats, userID)
	var i GetDashboardStatsRow
	err := row.Scan(&i.TotalAssets, &i.TotalSize, &i.UniqueTypes)
	return i, err
}

const getRecentAssets = `-- name: GetRecentAssets :many
SELECT id, user_id, name, type, mime_type, size, hash, tags, metadata, created_at, updated_at FROM assets
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentAssetsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetRecentAssets(ctx context.Context, arg GetRecentAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, getRecentAssets, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.Hash,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByUser = `-- name: ListAssetsByUser :many
SELECT id, user_id, name, type, mime_type, size, hash, tags, metadata, created_at, updated_at FROM assets
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAssetsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAssetsByUser(ctx context.Context, arg ListAssetsByUserParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.Hash,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAssetsByName = `-- name: SearchAssetsByName :many
SELECT id, user_id, name, type, mime_type, size, hash, tags, metadata, created_at, updated_at FROM assets
WHERE user_id = $1 AND name ILIKE $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchAssetsByNameParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) SearchAssetsByName(ctx context.Context, arg SearchAssetsByNameParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, searchAssetsByName,
		arg.UserID,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.Hash,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetTags = `-- name: UpdateAssetTags :one
UPDATE assets
SET tags = $2
WHERE id = $1
RETURNING id, user_id, name, type, mime_type, size, hash, tags, metadata, created_at, updated_at
`

type UpdateAssetTagsParams struct {
	ID   pgtype.UUID `json:"id"`
	Tags []string    `json:"tags"`
}

func (q *Queries) UpdateAssetTags(ctx context.Context, arg UpdateAssetTagsParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAssetTags, arg.ID, arg.Tags)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.Hash,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
