// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cli_sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCliSession = `-- name: CreateCliSession :one
INSERT INTO cli_sessions (user_id, token_hash, label, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, label, ip_address, user_agent, last_used_at, expires_at, revoked_at, created_at
`

type CreateCliSessionParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Label     *string            `json:"label"`
	IpAddress *netip.Addr        `json:"ip_address"`
	UserAgent *string            `json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCliSession(ctx context.Context, arg CreateCliSessionParams) (CliSession, error) {
	row := q.db.QueryRow(ctx, createCliSession,
		arg.UserID,
		arg.TokenHash,
		arg.Label,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i CliSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Label,
		&i.IpAddress,
		&i.UserAgent,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, user_id, token_hash, label, ip_address, user_agent, last_used_at, expires_at, revoked_at, created_at FROM cli_sessions
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenHash string) (CliSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, tokenHash)
	var i CliSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Label,
		&i.IpAddress,
		&i.UserAgent,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT id, user_id, token_hash, label, ip_address, user_agent, last_used_at, expires_at, revoked_at, created_at FROM cli_sessions
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessionsByUser(ctx context.Context, userID int64) ([]CliSession, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CliSession{}
	for rows.Next() {
		var i CliSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Label,
			&i.IpAddress,
			&i.UserAgent,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE cli_sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE cli_sessions
SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int64     `json:"user_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSessionLastUsed = `-- name: TouchSessionLastUsed :exec
UPDATE cli_sessions
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchSessionLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSessionLastUsed, id)
	return err
}
