// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveJobHealth = `-- name: ArchiveJobHealth :one
SELECT
    count(*) FILTER (WHERE status = 'pending')   AS pending,
    count(*) FILTER (WHERE status = 'running')   AS running,
    count(*) FILTER (WHERE status = 'completed') AS completed,
    count(*) FILTER (WHERE status = 'failed')    AS failed
FROM archive_sync_jobs
`

type ArchiveJobHealthRow struct {
	Pending   int64 `json:"pending"`
	Running   int64 `json:"running"`
	Completed int64 `json:"completed"`
	Failed    int64 `json:"failed"`
}

func (q *Queries) ArchiveJobHealth(ctx context.Context) (ArchiveJobHealthRow, error) {
	row := q.db.QueryRow(ctx, archiveJobHealth)
	var i ArchiveJobHealthRow
	err := row.Scan(
		&i.Pending,
		&i.Running,
		&i.Completed,
		&i.Failed,
	)
	return i, err
}

const galleryAssetCountsByType = `-- name: GalleryAssetCountsByType :many
SELECT type, count(*) AS count
FROM assets
WHERE gallery_id = $1 AND deleted_at IS NULL
GROUP BY type
ORDER BY count DESC
`

type GalleryAssetCountsByTypeRow struct {
	Type  string `json:"type"`
	Count int64  `json:"count"`
}

func (q *Queries) GalleryAssetCountsByType(ctx context.Context, galleryID int64) ([]GalleryAssetCountsByTypeRow, error) {
	rows, err := q.db.Query(ctx, galleryAssetCountsByType, galleryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GalleryAssetCountsByTypeRow{}
	for rows.Next() {
		var i GalleryAssetCountsByTypeRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const galleryAssetStats = `-- name: GalleryAssetStats :one
SELECT
    count(*)                        AS total_assets,
    COALESCE(sum(size), 0)::bigint  AS total_size,
    count(DISTINCT type)            AS type_count
FROM assets
WHERE gallery_id = $1 AND deleted_at IS NULL
`

type GalleryAssetStatsRow struct {
	TotalAssets int64 `json:"total_assets"`
	TotalSize   int64 `json:"total_size"`
	TypeCount   int64 `json:"type_count"`
}

func (q *Queries) GalleryAssetStats(ctx context.Context, galleryID int64) (GalleryAssetStatsRow, error) {
	row := q.db.QueryRow(ctx, galleryAssetStats, galleryID)
	var i GalleryAssetStatsRow
	err := row.Scan(&i.TotalAssets, &i.TotalSize, &i.TypeCount)
	return i, err
}

const galleryRecentAssets = `-- name: GalleryRecentAssets :many
SELECT id, name, type, mime_type, size, created_at
FROM assets
WHERE gallery_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type GalleryRecentAssetsParams struct {
	GalleryID int64 `json:"gallery_id"`
	Limit     int32 `json:"limit"`
}

type GalleryRecentAssetsRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	MimeType  string    `json:"mime_type"`
	Size      int64     `json:"size"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GalleryRecentAssets(ctx context.Context, arg GalleryRecentAssetsParams) ([]GalleryRecentAssetsRow, error) {
	rows, err := q.db.Query(ctx, galleryRecentAssets, arg.GalleryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GalleryRecentAssetsRow{}
	for rows.Next() {
		var i GalleryRecentAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
