// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package db

import (
	"context"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (space_id, parent_id, owner_id, name, path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, space_id, parent_id, owner_id, name, path, created_at, updated_at
`

type CreateFolderParams struct {
	SpaceID  int64  `json:"space_id"`
	ParentID *int64 `json:"parent_id"`
	OwnerID  int64  `json:"owner_id"`
	Name     string `json:"name"`
	Path     string `json:"path"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.SpaceID,
		arg.ParentID,
		arg.OwnerID,
		arg.Name,
		arg.Path,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ParentID,
		&i.OwnerID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = $1
`

func (q *Queries) DeleteFolder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const getFolderBreadcrumb = `-- name: GetFolderBreadcrumb :many
SELECT id, name, parent_id, path FROM folders
WHERE id = ANY($1::bigint[])
ORDER BY path
`

type GetFolderBreadcrumbRow struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	ParentID *int64 `json:"parent_id"`
	Path     string `json:"path"`
}

// Returns ancestor folders for breadcrumb display. Caller passes comma-separated
// IDs parsed from the folder's path field.
func (q *Queries) GetFolderBreadcrumb(ctx context.Context, dollar_1 []int64) ([]GetFolderBreadcrumbRow, error) {
	rows, err := q.db.Query(ctx, getFolderBreadcrumb, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFolderBreadcrumbRow{}
	for rows.Next() {
		var i GetFolderBreadcrumbRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, space_id, parent_id, owner_id, name, path, created_at, updated_at FROM folders WHERE id = $1
`

func (q *Queries) GetFolderByID(ctx context.Context, id int64) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ParentID,
		&i.OwnerID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFolderSubtree = `-- name: ListFolderSubtree :many
SELECT id, space_id, parent_id, owner_id, name, path, created_at, updated_at FROM folders
WHERE space_id = $1 AND path LIKE $2
ORDER BY path, name
`

type ListFolderSubtreeParams struct {
	SpaceID int64  `json:"space_id"`
	Path    string `json:"path"`
}

// Returns all descendants of a folder by matching the materialized path prefix.
// The path pattern should be passed as '/parentId/%' (e.g. '/5/%' or '/5/12/%').
func (q *Queries) ListFolderSubtree(ctx context.Context, arg ListFolderSubtreeParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFolderSubtree, arg.SpaceID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ParentID,
			&i.OwnerID,
			&i.Name,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByParent = `-- name: ListFoldersByParent :many
SELECT id, space_id, parent_id, owner_id, name, path, created_at, updated_at FROM folders
WHERE space_id = $1 AND parent_id = $2
ORDER BY name
`

type ListFoldersByParentParams struct {
	SpaceID  int64  `json:"space_id"`
	ParentID *int64 `json:"parent_id"`
}

func (q *Queries) ListFoldersByParent(ctx context.Context, arg ListFoldersByParentParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByParent, arg.SpaceID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ParentID,
			&i.OwnerID,
			&i.Name,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFolders = `-- name: ListRootFolders :many
SELECT id, space_id, parent_id, owner_id, name, path, created_at, updated_at FROM folders
WHERE space_id = $1 AND parent_id IS NULL
ORDER BY name
`

func (q *Queries) ListRootFolders(ctx context.Context, spaceID int64) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listRootFolders, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ParentID,
			&i.OwnerID,
			&i.Name,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolderName = `-- name: UpdateFolderName :one
UPDATE folders SET name = $2 WHERE id = $1 RETURNING id, space_id, parent_id, owner_id, name, path, created_at, updated_at
`

type UpdateFolderNameParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateFolderName(ctx context.Context, arg UpdateFolderNameParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolderName, arg.ID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ParentID,
		&i.OwnerID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFolderParent = `-- name: UpdateFolderParent :one
UPDATE folders SET parent_id = $2, path = $3 WHERE id = $1 RETURNING id, space_id, parent_id, owner_id, name, path, created_at, updated_at
`

type UpdateFolderParentParams struct {
	ID       int64  `json:"id"`
	ParentID *int64 `json:"parent_id"`
	Path     string `json:"path"`
}

func (q *Queries) UpdateFolderParent(ctx context.Context, arg UpdateFolderParentParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolderParent, arg.ID, arg.ParentID, arg.Path)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ParentID,
		&i.OwnerID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFolderPath = `-- name: UpdateFolderPath :exec
UPDATE folders SET path = $2 WHERE id = $1
`

type UpdateFolderPathParams struct {
	ID   int64  `json:"id"`
	Path string `json:"path"`
}

func (q *Queries) UpdateFolderPath(ctx context.Context, arg UpdateFolderPathParams) error {
	_, err := q.db.Exec(ctx, updateFolderPath, arg.ID, arg.Path)
	return err
}
