// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: galleries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGallery = `-- name: CreateGallery :one
INSERT INTO galleries (owner_id, name, description, is_default)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, description, is_default, storage_quota, storage_used, created_at, updated_at
`

type CreateGalleryParams struct {
	OwnerID     int64   `json:"owner_id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsDefault   bool    `json:"is_default"`
}

func (q *Queries) CreateGallery(ctx context.Context, arg CreateGalleryParams) (Gallery, error) {
	row := q.db.QueryRow(ctx, createGallery,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.IsDefault,
	)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGalleryInvitation = `-- name: CreateGalleryInvitation :one
INSERT INTO invitations (gallery_id, email, role, token, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, gallery_id, album_id, email, role, token, status, invited_by, accepted_user_id, expires_at, accepted_at, created_at, updated_at
`

type CreateGalleryInvitationParams struct {
	GalleryID *int64             `json:"gallery_id"`
	Email     string             `json:"email"`
	Role      MemberRole         `json:"role"`
	Token     string             `json:"token"`
	InvitedBy *int64             `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateGalleryInvitation(ctx context.Context, arg CreateGalleryInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createGalleryInvitation,
		arg.GalleryID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.AlbumID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.AcceptedUserID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGallery = `-- name: DeleteGallery :exec
DELETE FROM galleries WHERE id = $1
`

func (q *Queries) DeleteGallery(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGallery, id)
	return err
}

const getDefaultGallery = `-- name: GetDefaultGallery :one
SELECT id, owner_id, name, description, is_default, storage_quota, storage_used, created_at, updated_at FROM galleries WHERE owner_id = $1 AND is_default = TRUE
`

func (q *Queries) GetDefaultGallery(ctx context.Context, ownerID int64) (Gallery, error) {
	row := q.db.QueryRow(ctx, getDefaultGallery, ownerID)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGalleryByID = `-- name: GetGalleryByID :one
SELECT id, owner_id, name, description, is_default, storage_quota, storage_used, created_at, updated_at FROM galleries WHERE id = $1
`

func (q *Queries) GetGalleryByID(ctx context.Context, id int64) (Gallery, error) {
	row := q.db.QueryRow(ctx, getGalleryByID, id)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGalleryMember = `-- name: GetGalleryMember :one
SELECT gallery_id, user_id, role, invited_by, created_at FROM gallery_members WHERE gallery_id = $1 AND user_id = $2
`

type GetGalleryMemberParams struct {
	GalleryID int64 `json:"gallery_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) GetGalleryMember(ctx context.Context, arg GetGalleryMemberParams) (GalleryMember, error) {
	row := q.db.QueryRow(ctx, getGalleryMember, arg.GalleryID, arg.UserID)
	var i GalleryMember
	err := row.Scan(
		&i.GalleryID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, gallery_id, album_id, email, role, token, status, invited_by, accepted_user_id, expires_at, accepted_at, created_at, updated_at FROM invitations WHERE token = $1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.AlbumID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.AcceptedUserID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGalleriesForUser = `-- name: ListGalleriesForUser :many
SELECT g.id, g.owner_id, g.name, g.description, g.is_default, g.storage_quota, g.storage_used, g.created_at, g.updated_at
FROM galleries g
JOIN gallery_members gm ON gm.gallery_id = g.id
WHERE gm.user_id = $1
ORDER BY g.created_at
`

func (q *Queries) ListGalleriesForUser(ctx context.Context, userID int64) ([]Gallery, error) {
	rows, err := q.db.Query(ctx, listGalleriesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gallery{}
	for rows.Next() {
		var i Gallery
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.IsDefault,
			&i.StorageQuota,
			&i.StorageUsed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGalleryInvitations = `-- name: ListGalleryInvitations :many
SELECT id, gallery_id, album_id, email, role, token, status, invited_by, accepted_user_id, expires_at, accepted_at, created_at, updated_at FROM invitations
WHERE gallery_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListGalleryInvitations(ctx context.Context, galleryID *int64) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listGalleryInvitations, galleryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.GalleryID,
			&i.AlbumID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.Status,
			&i.InvitedBy,
			&i.AcceptedUserID,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGalleryMembers = `-- name: ListGalleryMembers :many
SELECT gm.gallery_id, gm.user_id, gm.role, gm.created_at,
       u.email, u.name, u.avatar_url
FROM gallery_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.gallery_id = $1
ORDER BY gm.created_at
`

type ListGalleryMembersRow struct {
	GalleryID int64      `json:"gallery_id"`
	UserID    int64      `json:"user_id"`
	Role      MemberRole `json:"role"`
	CreatedAt time.Time  `json:"created_at"`
	Email     string     `json:"email"`
	Name      string     `json:"name"`
	AvatarUrl *string    `json:"avatar_url"`
}

func (q *Queries) ListGalleryMembers(ctx context.Context, galleryID int64) ([]ListGalleryMembersRow, error) {
	rows, err := q.db.Query(ctx, listGalleryMembers, galleryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGalleryMembersRow{}
	for rows.Next() {
		var i ListGalleryMembersRow
		if err := rows.Scan(
			&i.GalleryID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE invitations
SET status = 'accepted', accepted_user_id = $2, accepted_at = now()
WHERE id = $1
`

type MarkInvitationAcceptedParams struct {
	ID             int64  `json:"id"`
	AcceptedUserID *int64 `json:"accepted_user_id"`
}

func (q *Queries) MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, arg.ID, arg.AcceptedUserID)
	return err
}

const removeGalleryMember = `-- name: RemoveGalleryMember :execrows
DELETE FROM gallery_members WHERE gallery_id = $1 AND user_id = $2
`

type RemoveGalleryMemberParams struct {
	GalleryID int64 `json:"gallery_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) RemoveGalleryMember(ctx context.Context, arg RemoveGalleryMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGalleryMember, arg.GalleryID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeGalleryInvitation = `-- name: RevokeGalleryInvitation :execrows
UPDATE invitations
SET status = 'revoked'
WHERE id = $1 AND gallery_id = $2 AND status = 'pending'
`

type RevokeGalleryInvitationParams struct {
	ID        int64  `json:"id"`
	GalleryID *int64 `json:"gallery_id"`
}

func (q *Queries) RevokeGalleryInvitation(ctx context.Context, arg RevokeGalleryInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeGalleryInvitation, arg.ID, arg.GalleryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGallery = `-- name: UpdateGallery :one
UPDATE galleries
SET name = $2, description = $3
WHERE id = $1
RETURNING id, owner_id, name, description, is_default, storage_quota, storage_used, created_at, updated_at
`

type UpdateGalleryParams struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateGallery(ctx context.Context, arg UpdateGalleryParams) (Gallery, error) {
	row := q.db.QueryRow(ctx, updateGallery, arg.ID, arg.Name, arg.Description)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGalleryMemberRole = `-- name: UpdateGalleryMemberRole :execrows
UPDATE gallery_members SET role = $3 WHERE gallery_id = $1 AND user_id = $2
`

type UpdateGalleryMemberRoleParams struct {
	GalleryID int64      `json:"gallery_id"`
	UserID    int64      `json:"user_id"`
	Role      MemberRole `json:"role"`
}

func (q *Queries) UpdateGalleryMemberRole(ctx context.Context, arg UpdateGalleryMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGalleryMemberRole, arg.GalleryID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertGalleryMember = `-- name: UpsertGalleryMember :exec
INSERT INTO gallery_members (gallery_id, user_id, role, invited_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (gallery_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertGalleryMemberParams struct {
	GalleryID int64      `json:"gallery_id"`
	UserID    int64      `json:"user_id"`
	Role      MemberRole `json:"role"`
	InvitedBy *int64     `json:"invited_by"`
}

func (q *Queries) UpsertGalleryMember(ctx context.Context, arg UpsertGalleryMemberParams) error {
	_, err := q.db.Exec(ctx, upsertGalleryMember,
		arg.GalleryID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	return err
}
