// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimArchiveJob = `-- name: ClaimArchiveJob :one
UPDATE archive_sync_jobs
SET status = 'running', attempts = attempts + 1, updated_at = now()
WHERE id = (
    SELECT id FROM archive_sync_jobs
    WHERE status = 'pending'
      AND (next_retry_at IS NULL OR next_retry_at <= now())
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, asset_id, target_layer, provider_id, status, attempts, max_attempts, last_error, next_retry_at, created_at, updated_at
`

// Atomically claims the next due archive job (skipping locked rows) and marks
// it running. Returns no rows when the queue is empty.
func (q *Queries) ClaimArchiveJob(ctx context.Context) (ArchiveSyncJob, error) {
	row := q.db.QueryRow(ctx, claimArchiveJob)
	var i ArchiveSyncJob
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.TargetLayer,
		&i.ProviderID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArchiveSource = `-- name: GetArchiveSource :one
SELECT a.size, a.mime_type, sl.provider_id, sl.provider_key
FROM assets a
JOIN storage_locations sl
  ON sl.asset_id = a.id AND sl.layer = 'serving' AND sl.status = 'stored'
WHERE a.id = $1
LIMIT 1
`

type GetArchiveSourceRow struct {
	Size        int64  `json:"size"`
	MimeType    string `json:"mime_type"`
	ProviderID  int64  `json:"provider_id"`
	ProviderKey string `json:"provider_key"`
}

func (q *Queries) GetArchiveSource(ctx context.Context, id uuid.UUID) (GetArchiveSourceRow, error) {
	row := q.db.QueryRow(ctx, getArchiveSource, id)
	var i GetArchiveSourceRow
	err := row.Scan(
		&i.Size,
		&i.MimeType,
		&i.ProviderID,
		&i.ProviderKey,
	)
	return i, err
}

const markArchiveJobResult = `-- name: MarkArchiveJobResult :exec
UPDATE archive_sync_jobs
SET status = $2, last_error = $3, next_retry_at = $4, updated_at = now()
WHERE id = $1
`

type MarkArchiveJobResultParams struct {
	ID          int64              `json:"id"`
	Status      JobStatus          `json:"status"`
	LastError   *string            `json:"last_error"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) MarkArchiveJobResult(ctx context.Context, arg MarkArchiveJobResultParams) error {
	_, err := q.db.Exec(ctx, markArchiveJobResult,
		arg.ID,
		arg.Status,
		arg.LastError,
		arg.NextRetryAt,
	)
	return err
}
