// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Name      string           `json:"name"`
	Type      string           `json:"type"`
	MimeType  string           `json:"mime_type"`
	Size      int64            `json:"size"`
	Hash      string           `json:"hash"`
	Tags      []string         `json:"tags"`
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type StorageLocation struct {
	ID          pgtype.UUID      `json:"id"`
	AssetID     pgtype.UUID      `json:"asset_id"`
	ProviderID  pgtype.UUID      `json:"provider_id"`
	ProviderKey string           `json:"provider_key"`
	Url         string           `json:"url"`
	Metadata    []byte           `json:"metadata"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type StorageProvider struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	Name        string           `json:"name"`
	Type        string           `json:"type"`
	Credentials []byte           `json:"credentials"`
	Quota       *int64           `json:"quota"`
	Used        int64            `json:"used"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Email        string           `json:"email"`
	Name         string           `json:"name"`
	PasswordHash string           `json:"password_hash"`
	StorageQuota int64            `json:"storage_quota"`
	StorageUsed  int64            `json:"storage_used"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
