// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InvitationStatus string

const (
	InvitationStatusPending  InvitationStatus = "pending"
	InvitationStatusAccepted InvitationStatus = "accepted"
	InvitationStatusRevoked  InvitationStatus = "revoked"
	InvitationStatusExpired  InvitationStatus = "expired"
)

func (e *InvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationStatus(s)
	case string:
		*e = InvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationStatus: %T", src)
	}
	return nil
}

type NullInvitationStatus struct {
	InvitationStatus InvitationStatus `json:"invitation_status"`
	Valid            bool             `json:"valid"` // Valid is true if InvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationStatus), nil
}

type JobStatus string

const (
	JobStatusPending   JobStatus = "pending"
	JobStatusRunning   JobStatus = "running"
	JobStatusCompleted JobStatus = "completed"
	JobStatusFailed    JobStatus = "failed"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type LocationStatus string

const (
	LocationStatusPending LocationStatus = "pending"
	LocationStatusStored  LocationStatus = "stored"
	LocationStatusFailed  LocationStatus = "failed"
)

func (e *LocationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocationStatus(s)
	case string:
		*e = LocationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LocationStatus: %T", src)
	}
	return nil
}

type NullLocationStatus struct {
	LocationStatus LocationStatus `json:"location_status"`
	Valid          bool           `json:"valid"` // Valid is true if LocationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LocationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocationStatus), nil
}

type MemberRole string

const (
	MemberRoleOwner  MemberRole = "owner"
	MemberRoleEditor MemberRole = "editor"
	MemberRoleViewer MemberRole = "viewer"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type PermissionScope string

const (
	PermissionScopeOwn PermissionScope = "own"
	PermissionScopeAll PermissionScope = "all"
)

func (e *PermissionScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionScope(s)
	case string:
		*e = PermissionScope(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionScope: %T", src)
	}
	return nil
}

type NullPermissionScope struct {
	PermissionScope PermissionScope `json:"permission_scope"`
	Valid           bool            `json:"valid"` // Valid is true if PermissionScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionScope) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionScope), nil
}

type StorageLayer string

const (
	StorageLayerServing StorageLayer = "serving"
	StorageLayerArchive StorageLayer = "archive"
)

func (e *StorageLayer) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StorageLayer(s)
	case string:
		*e = StorageLayer(s)
	default:
		return fmt.Errorf("unsupported scan type for StorageLayer: %T", src)
	}
	return nil
}

type NullStorageLayer struct {
	StorageLayer StorageLayer `json:"storage_layer"`
	Valid        bool         `json:"valid"` // Valid is true if StorageLayer is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStorageLayer) Scan(value interface{}) error {
	if value == nil {
		ns.StorageLayer, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StorageLayer.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStorageLayer) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StorageLayer), nil
}

type Album struct {
	ID           int64       `json:"id"`
	GalleryID    int64       `json:"gallery_id"`
	OwnerID      int64       `json:"owner_id"`
	Name         string      `json:"name"`
	Description  *string     `json:"description"`
	CoverAssetID pgtype.UUID `json:"cover_asset_id"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type AlbumAsset struct {
	AlbumID   int64     `json:"album_id"`
	AssetID   uuid.UUID `json:"asset_id"`
	AddedBy   *int64    `json:"added_by"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type AlbumMember struct {
	AlbumID   int64      `json:"album_id"`
	UserID    int64      `json:"user_id"`
	Role      MemberRole `json:"role"`
	InvitedBy *int64     `json:"invited_by"`
	CreatedAt time.Time  `json:"created_at"`
}

type ArchiveSyncJob struct {
	ID          int64              `json:"id"`
	AssetID     uuid.UUID          `json:"asset_id"`
	TargetLayer StorageLayer       `json:"target_layer"`
	ProviderID  *int64             `json:"provider_id"`
	Status      JobStatus          `json:"status"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	LastError   *string            `json:"last_error"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type Asset struct {
	ID         uuid.UUID          `json:"id"`
	GalleryID  int64              `json:"gallery_id"`
	UploadedBy *int64             `json:"uploaded_by"`
	Name       string             `json:"name"`
	Type       string             `json:"type"`
	MimeType   string             `json:"mime_type"`
	Size       int64              `json:"size"`
	Hash       string             `json:"hash"`
	Metadata   []byte             `json:"metadata"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy  *int64             `json:"deleted_by"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

type AssetTag struct {
	AssetID   uuid.UUID `json:"asset_id"`
	TagID     int64     `json:"tag_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ClerkWebhookEvent struct {
	ID          int64              `json:"id"`
	EventID     string             `json:"event_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	Error       *string            `json:"error"`
	ReceivedAt  time.Time          `json:"received_at"`
}

type CliSession struct {
	ID         uuid.UUID          `json:"id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	Label      *string            `json:"label"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  *string            `json:"user_agent"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type Gallery struct {
	ID           int64     `json:"id"`
	OwnerID      int64     `json:"owner_id"`
	Name         string    `json:"name"`
	Description  *string   `json:"description"`
	IsDefault    bool      `json:"is_default"`
	StorageQuota int64     `json:"storage_quota"`
	StorageUsed  int64     `json:"storage_used"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type GalleryMember struct {
	GalleryID int64      `json:"gallery_id"`
	UserID    int64      `json:"user_id"`
	Role      MemberRole `json:"role"`
	InvitedBy *int64     `json:"invited_by"`
	CreatedAt time.Time  `json:"created_at"`
}

type Invitation struct {
	ID             int64              `json:"id"`
	GalleryID      *int64             `json:"gallery_id"`
	AlbumID        *int64             `json:"album_id"`
	Email          string             `json:"email"`
	Role           MemberRole         `json:"role"`
	Token          string             `json:"token"`
	Status         InvitationStatus   `json:"status"`
	InvitedBy      *int64             `json:"invited_by"`
	AcceptedUserID *int64             `json:"accepted_user_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type Permission struct {
	ID          int64     `json:"id"`
	Resource    string    `json:"resource"`
	Action      string    `json:"action"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Role struct {
	ID          int64     `json:"id"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RolePermission struct {
	RoleID       int64           `json:"role_id"`
	PermissionID int64           `json:"permission_id"`
	Scope        PermissionScope `json:"scope"`
	CreatedAt    time.Time       `json:"created_at"`
}

type StorageAccountUsage struct {
	ID            int64        `json:"id"`
	Name          string       `json:"name"`
	Layer         StorageLayer `json:"layer"`
	Type          string       `json:"type"`
	IsActive      bool         `json:"is_active"`
	Quota         *int64       `json:"quota"`
	Used          int64        `json:"used"`
	UsedPercent   interface{}  `json:"used_percent"`
	LocationCount int64        `json:"location_count"`
	StoredCount   int64        `json:"stored_count"`
	PendingCount  int64        `json:"pending_count"`
	FailedCount   int64        `json:"failed_count"`
}

type StorageLocation struct {
	ID          uuid.UUID      `json:"id"`
	AssetID     uuid.UUID      `json:"asset_id"`
	ProviderID  int64          `json:"provider_id"`
	Layer       StorageLayer   `json:"layer"`
	ProviderKey string         `json:"provider_key"`
	Url         *string        `json:"url"`
	Status      LocationStatus `json:"status"`
	Metadata    []byte         `json:"metadata"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type StorageProvider struct {
	ID          int64        `json:"id"`
	Layer       StorageLayer `json:"layer"`
	Name        string       `json:"name"`
	Type        string       `json:"type"`
	Credentials []byte       `json:"credentials"`
	Quota       *int64       `json:"quota"`
	Used        int64        `json:"used"`
	IsActive    bool         `json:"is_active"`
	CreatedBy   *int64       `json:"created_by"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

type Tag struct {
	ID        int64     `json:"id"`
	GalleryID int64     `json:"gallery_id"`
	Name      string    `json:"name"`
	CreatedBy *int64    `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID          int64              `json:"id"`
	ClerkUserID string             `json:"clerk_user_id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	AvatarUrl   *string            `json:"avatar_url"`
	IsActive    bool               `json:"is_active"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type UserRole struct {
	UserID    int64     `json:"user_id"`
	RoleID    int64     `json:"role_id"`
	GrantedBy *int64    `json:"granted_by"`
	CreatedAt time.Time `json:"created_at"`
}
