// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO storage_providers (
    user_id,
    name,
    type,
    credentials,
    quota
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, name, type, credentials, quota, used, is_active, created_at, updated_at
`

type CreateProviderParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Credentials []byte      `json:"credentials"`
	Quota       *int64      `json:"quota"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Credentials,
		arg.Quota,
	)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Credentials,
		&i.Quota,
		&i.Used,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStorageLocation = `-- name: CreateStorageLocation :one
INSERT INTO storage_locations (
    asset_id,
    provider_id,
    provider_key,
    url,
    metadata
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, asset_id, provider_id, provider_key, url, metadata, created_at
`

type CreateStorageLocationParams struct {
	AssetID     pgtype.UUID `json:"asset_id"`
	ProviderID  pgtype.UUID `json:"provider_id"`
	ProviderKey string      `json:"provider_key"`
	Url         string      `json:"url"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateStorageLocation(ctx context.Context, arg CreateStorageLocationParams) (StorageLocation, error) {
	row := q.db.QueryRow(ctx, createStorageLocation,
		arg.AssetID,
		arg.ProviderID,
		arg.ProviderKey,
		arg.Url,
		arg.Metadata,
	)
	var i StorageLocation
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ProviderID,
		&i.ProviderKey,
		&i.Url,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateProvider = `-- name: DeactivateProvider :one
UPDATE storage_providers
SET is_active = false
WHERE id = $1
RETURNING id, user_id, name, type, credentials, quota, used, is_active, created_at, updated_at
`

func (q *Queries) DeactivateProvider(ctx context.Context, id pgtype.UUID) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, deactivateProvider, id)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Credentials,
		&i.Quota,
		&i.Used,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM storage_locations
WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const getLocationsByAssetID = `-- name: GetLocationsByAssetID :many
SELECT id, asset_id, provider_id, provider_key, url, metadata, created_at FROM storage_locations
WHERE asset_id = $1
`

func (q *Queries) GetLocationsByAssetID(ctx context.Context, assetID pgtype.UUID) ([]StorageLocation, error) {
	rows, err := q.db.Query(ctx, getLocationsByAssetID, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageLocation{}
	for rows.Next() {
		var i StorageLocation
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.ProviderID,
			&i.ProviderKey,
			&i.Url,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, user_id, name, type, credentials, quota, used, is_active, created_at, updated_at FROM storage_providers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProviderByID(ctx context.Context, id pgtype.UUID) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Credentials,
		&i.Quota,
		&i.Used,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProvidersByUser = `-- name: ListActiveProvidersByUser :many
SELECT id, user_id, name, type, credentials, quota, used, is_active, created_at, updated_at FROM storage_providers
WHERE user_id = $1 AND is_active = true
ORDER BY created_at
`

func (q *Queries) ListActiveProvidersByUser(ctx context.Context, userID pgtype.UUID) ([]StorageProvider, error) {
	rows, err := q.db.Query(ctx, listActiveProvidersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageProvider{}
	for rows.Next() {
		var i StorageProvider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Credentials,
			&i.Quota,
			&i.Used,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProvidersByUser = `-- name: ListAllProvidersByUser :many
SELECT id, user_id, name, type, credentials, quota, used, is_active, created_at, updated_at FROM storage_providers
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAllProvidersByUser(ctx context.Context, userID pgtype.UUID) ([]StorageProvider, error) {
	rows, err := q.db.Query(ctx, listAllProvidersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageProvider{}
	for rows.Next() {
		var i StorageProvider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Credentials,
			&i.Quota,
			&i.Used,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderUsage = `-- name: UpdateProviderUsage :one
UPDATE storage_providers
SET used = $2
WHERE id = $1
RETURNING id, user_id, name, type, credentials, quota, used, is_active, created_at, updated_at
`

type UpdateProviderUsageParams struct {
	ID   pgtype.UUID `json:"id"`
	Used int64       `json:"used"`
}

func (q *Queries) UpdateProviderUsage(ctx context.Context, arg UpdateProviderUsageParams) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, updateProviderUsage, arg.ID, arg.Used)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Credentials,
		&i.Quota,
		&i.Used,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
