// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package db

import (
	"context"
)

const addStorageProviderUsed = `-- name: AddStorageProviderUsed :exec
UPDATE storage_providers SET used = used + $2 WHERE id = $1
`

type AddStorageProviderUsedParams struct {
	ID   int64 `json:"id"`
	Used int64 `json:"used"`
}

func (q *Queries) AddStorageProviderUsed(ctx context.Context, arg AddStorageProviderUsedParams) error {
	_, err := q.db.Exec(ctx, addStorageProviderUsed, arg.ID, arg.Used)
	return err
}

const createStorageProvider = `-- name: CreateStorageProvider :one
INSERT INTO storage_providers (layer, name, type, credentials, quota, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, layer, name, type, credentials, quota, used, is_active, created_by, created_at, updated_at
`

type CreateStorageProviderParams struct {
	Layer       StorageLayer `json:"layer"`
	Name        string       `json:"name"`
	Type        string       `json:"type"`
	Credentials []byte       `json:"credentials"`
	Quota       *int64       `json:"quota"`
	CreatedBy   *int64       `json:"created_by"`
}

func (q *Queries) CreateStorageProvider(ctx context.Context, arg CreateStorageProviderParams) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, createStorageProvider,
		arg.Layer,
		arg.Name,
		arg.Type,
		arg.Credentials,
		arg.Quota,
		arg.CreatedBy,
	)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Layer,
		&i.Name,
		&i.Type,
		&i.Credentials,
		&i.Quota,
		&i.Used,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateStorageProvider = `-- name: DeactivateStorageProvider :exec
UPDATE storage_providers SET is_active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateStorageProvider(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateStorageProvider, id)
	return err
}

const getStorageProvider = `-- name: GetStorageProvider :one
SELECT id, layer, name, type, credentials, quota, used, is_active, created_by, created_at, updated_at FROM storage_providers WHERE id = $1
`

func (q *Queries) GetStorageProvider(ctx context.Context, id int64) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, getStorageProvider, id)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Layer,
		&i.Name,
		&i.Type,
		&i.Credentials,
		&i.Quota,
		&i.Used,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProvidersByLayer = `-- name: ListActiveProvidersByLayer :many
SELECT id, layer, name, type, credentials, quota, used, is_active, created_by, created_at, updated_at FROM storage_providers
WHERE layer = $1 AND is_active = TRUE
ORDER BY id
`

func (q *Queries) ListActiveProvidersByLayer(ctx context.Context, layer StorageLayer) ([]StorageProvider, error) {
	rows, err := q.db.Query(ctx, listActiveProvidersByLayer, layer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageProvider{}
	for rows.Next() {
		var i StorageProvider
		if err := rows.Scan(
			&i.ID,
			&i.Layer,
			&i.Name,
			&i.Type,
			&i.Credentials,
			&i.Quota,
			&i.Used,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageAccountUsage = `-- name: ListStorageAccountUsage :many
SELECT id, name, layer, type, is_active, quota, used,
       COALESCE(used_percent, 0)::float8 AS used_percent,
       location_count, stored_count, pending_count, failed_count
FROM storage_account_usage
ORDER BY layer, name
`

type ListStorageAccountUsageRow struct {
	ID            int64        `json:"id"`
	Name          string       `json:"name"`
	Layer         StorageLayer `json:"layer"`
	Type          string       `json:"type"`
	IsActive      bool         `json:"is_active"`
	Quota         *int64       `json:"quota"`
	Used          int64        `json:"used"`
	UsedPercent   float64      `json:"used_percent"`
	LocationCount int64        `json:"location_count"`
	StoredCount   int64        `json:"stored_count"`
	PendingCount  int64        `json:"pending_count"`
	FailedCount   int64        `json:"failed_count"`
}

func (q *Queries) ListStorageAccountUsage(ctx context.Context) ([]ListStorageAccountUsageRow, error) {
	rows, err := q.db.Query(ctx, listStorageAccountUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorageAccountUsageRow{}
	for rows.Next() {
		var i ListStorageAccountUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Layer,
			&i.Type,
			&i.IsActive,
			&i.Quota,
			&i.Used,
			&i.UsedPercent,
			&i.LocationCount,
			&i.StoredCount,
			&i.PendingCount,
			&i.FailedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageProviders = `-- name: ListStorageProviders :many
SELECT id, layer, name, type, credentials, quota, used, is_active, created_by, created_at, updated_at FROM storage_providers ORDER BY layer, name
`

func (q *Queries) ListStorageProviders(ctx context.Context) ([]StorageProvider, error) {
	rows, err := q.db.Query(ctx, listStorageProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageProvider{}
	for rows.Next() {
		var i StorageProvider
		if err := rows.Scan(
			&i.ID,
			&i.Layer,
			&i.Name,
			&i.Type,
			&i.Credentials,
			&i.Quota,
			&i.Used,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStorageProvider = `-- name: UpdateStorageProvider :one
UPDATE storage_providers
SET name = $2, credentials = $3, quota = $4, is_active = $5
WHERE id = $1
RETURNING id, layer, name, type, credentials, quota, used, is_active, created_by, created_at, updated_at
`

type UpdateStorageProviderParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Credentials []byte `json:"credentials"`
	Quota       *int64 `json:"quota"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) UpdateStorageProvider(ctx context.Context, arg UpdateStorageProviderParams) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, updateStorageProvider,
		arg.ID,
		arg.Name,
		arg.Credentials,
		arg.Quota,
		arg.IsActive,
	)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Layer,
		&i.Name,
		&i.Type,
		&i.Credentials,
		&i.Quota,
		&i.Used,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
