// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const attachTag = `-- name: AttachTag :exec
INSERT INTO asset_tags (asset_id, tag_id)
VALUES ($1, $2)
ON CONFLICT (asset_id, tag_id) DO NOTHING
`

type AttachTagParams struct {
	AssetID uuid.UUID `json:"asset_id"`
	TagID   int64     `json:"tag_id"`
}

func (q *Queries) AttachTag(ctx context.Context, arg AttachTagParams) error {
	_, err := q.db.Exec(ctx, attachTag, arg.AssetID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (gallery_id, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, gallery_id, name, created_by, created_at, updated_at
`

type CreateTagParams struct {
	GalleryID int64  `json:"gallery_id"`
	Name      string `json:"name"`
	CreatedBy *int64 `json:"created_by"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.GalleryID, arg.Name, arg.CreatedBy)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const detachTag = `-- name: DetachTag :execrows
DELETE FROM asset_tags WHERE asset_id = $1 AND tag_id = $2
`

type DetachTagParams struct {
	AssetID uuid.UUID `json:"asset_id"`
	TagID   int64     `json:"tag_id"`
}

func (q *Queries) DetachTag(ctx context.Context, arg DetachTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, detachTag, arg.AssetID, arg.TagID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, gallery_id, name, created_by, created_at, updated_at FROM tags WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssetTags = `-- name: ListAssetTags :many
SELECT t.id, t.gallery_id, t.name, t.created_by, t.created_at, t.updated_at
FROM asset_tags at
JOIN tags t ON t.id = at.tag_id
WHERE at.asset_id = $1
ORDER BY t.name
`

func (q *Queries) ListAssetTags(ctx context.Context, assetID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listAssetTags, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.GalleryID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByGallery = `-- name: ListTagsByGallery :many
SELECT id, gallery_id, name, created_by, created_at, updated_at FROM tags WHERE gallery_id = $1 ORDER BY name
`

func (q *Queries) ListTagsByGallery(ctx context.Context, galleryID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByGallery, galleryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.GalleryID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET name = $2 WHERE id = $1 RETURNING id, gallery_id, name, created_by, created_at, updated_at
`

type UpdateTagParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
