/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSpacesSpaceIdRouteImport } from './routes/_authenticated/spaces/$spaceId'
import { Route as AuthenticatedSpacesSpaceIdIndexRouteImport } from './routes/_authenticated/spaces/$spaceId/index'
import { Route as AuthenticatedSpacesSpaceIdFoldersFolderIdRouteImport } from './routes/_authenticated/spaces/$spaceId/folders/$folderId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpacesSpaceIdRoute =
  AuthenticatedSpacesSpaceIdRouteImport.update({
    id: '/spaces/$spaceId',
    path: '/spaces/$spaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpacesSpaceIdIndexRoute =
  AuthenticatedSpacesSpaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)
const AuthenticatedSpacesSpaceIdFoldersFolderIdRoute =
  AuthenticatedSpacesSpaceIdFoldersFolderIdRouteImport.update({
    id: '/folders/$folderId',
    path: '/folders/$folderId',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdRouteWithChildren
  '/spaces/$spaceId/': typeof AuthenticatedSpacesSpaceIdIndexRoute
  '/spaces/$spaceId/folders/$folderId': typeof AuthenticatedSpacesSpaceIdFoldersFolderIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdIndexRoute
  '/spaces/$spaceId/folders/$folderId': typeof AuthenticatedSpacesSpaceIdFoldersFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdRouteWithChildren
  '/_authenticated/spaces/$spaceId/': typeof AuthenticatedSpacesSpaceIdIndexRoute
  '/_authenticated/spaces/$spaceId/folders/$folderId': typeof AuthenticatedSpacesSpaceIdFoldersFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/folders/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/folders/$folderId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/'
    | '/_authenticated/spaces/$spaceId'
    | '/_authenticated/spaces/$spaceId/'
    | '/_authenticated/spaces/$spaceId/folders/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/$spaceId': {
      id: '/_authenticated/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/$spaceId/': {
      id: '/_authenticated/spaces/$spaceId/'
      path: '/'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
    '/_authenticated/spaces/$spaceId/folders/$folderId': {
      id: '/_authenticated/spaces/$spaceId/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/spaces/$spaceId/folders/$folderId'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdFoldersFolderIdRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
  }
}

interface AuthenticatedSpacesSpaceIdRouteChildren {
  AuthenticatedSpacesSpaceIdIndexRoute: typeof AuthenticatedSpacesSpaceIdIndexRoute
  AuthenticatedSpacesSpaceIdFoldersFolderIdRoute: typeof AuthenticatedSpacesSpaceIdFoldersFolderIdRoute
}

const AuthenticatedSpacesSpaceIdRouteChildren: AuthenticatedSpacesSpaceIdRouteChildren =
  {
    AuthenticatedSpacesSpaceIdIndexRoute: AuthenticatedSpacesSpaceIdIndexRoute,
    AuthenticatedSpacesSpaceIdFoldersFolderIdRoute:
      AuthenticatedSpacesSpaceIdFoldersFolderIdRoute,
  }

const AuthenticatedSpacesSpaceIdRouteWithChildren =
  AuthenticatedSpacesSpaceIdRoute._addFileChildren(
    AuthenticatedSpacesSpaceIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSpacesSpaceIdRoute: typeof AuthenticatedSpacesSpaceIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSpacesSpaceIdRoute: AuthenticatedSpacesSpaceIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
